/**
 * Episode 1 — Jon Gordon (The Energy Bus)
 *
 * Source: Plaud auto-transcript, lightly sanitized:
 * - Speaker labels normalized (Speaker 1 → Seth Pepper, Speaker 2 → Jon Gordon)
 * - Name spelling normalized (Jon, not John)
 * - Two clear misattributions corrected
 * - Reformatted to [HH:MM:SS] Name blocks with paragraph breaks
 *
 * Original ASR voice/fillers preserved deliberately.
 */
export default `[00:00:03] Seth Pepper
Jon Gordon is a husband, father, and author. His bestselling books and talks have inspired millions of readers and audiences around the world. He is the author of the timeless classic "The Energy Bus," "The Carpenter Training Camp," "The Power of Positive Thinking," "The Power of Positive Leadership," and "The Power of Positive Leadership" by Jon Gordon. When he's not running through airports or speaking to businesses, hospitals, or schools, you can find him playing pickleball and taking long walks, which are when he gets most of his ideas. Jon believes in keeping his bio short because his past accomplishments are meaningless. What matters most is that he says something today that will inspire you to take action tomorrow. Welcome back to Unlimit Your Potential. Today we have a very special guest.

[00:01:03] Seth Pepper
This is a bestselling author, very well known speaker, Jon Gordon. Welcome to the show. This has been exciting just to know that you were in the building and that we're going to do this. So welcome.

[00:01:18] Jon Gordon
Good to hear. I've been looking forward to this.

[00:01:21] Seth Pepper
So your journey started. I was going through your origin story and the part that really stuck out. I always think this is interesting. In nature, the mother of invention is necessity, and so your wife kind of gave you an ultimatum early on. You are known for positivity. Your bestselling books and your speaking are about this positivity, and so as we go through life, we know we should be positive. But your wife really at the beginning said, "Hey, you need to work on this."

[00:01:58] Jon Gordon
It's ironic that this is my life's work, because I am not naturally positive. That's what's so funny about all this. God has a great sense of humor. I am naturally negative. I grew up in Long Island, New York, in a Jewish Italian family. There is a lot of food, a lot of guilt. There is a lot of wine, a lot of whining. And my dad was a New York City police officer. Undercover narcotics, and so he was shot a few times. He wasn't very positive, my dad. A very loving man, but one of the most negative guys on the planet, and so growing up in that environment. I grew up with a lot of negativity.

[00:02:31] Jon Gordon
A lot of love, but a lot of negativity. I also struggled with negativity for a lot of my life. Depression, anxiety. I was so negative on the sports field as a Division One athlete. I never truly enjoyed playing. If I could go back, I would just enjoy it. I would just love playing. People always say, 'what do you regret?' I don't have many regrets, but that is one of them: that I didn't really make the most out of my college experience, being this lacrosse player at Cornell and always trying to be perfect. Always trying to have a great game. If I didn't have a great game, then I was a bad player. I was a bad person. Life stunk if I didn't have a great game. And so, I never truly understood what it meant to be a good person. So, I never truly enjoyed it. It was always fear—fear of not being enough. Fear of not playing well, fear of making a mistake, and losing my starting position. It wasn't love.

[00:03:29] Jon Gordon
And that's why I love doing what I do now because I get to bring positivity to people. I get to explain the importance of positivity and optimism and belief and why it matters so much. And so many of us naturally go towards the negative, and so many of us struggle with negativity and challenges and our mindset. And so again, I laugh as you were saying that because I am known as Mister Positive. I don't want to be known as that. I'm just the guy who actually writes these books that help people be positive. But if you look at my work, a lot of my characters in my fables are actually negative, and they need to rewire their brain. They have to change their thinking. They have to learn new ways to solve problems. It's like the Positive Thinking Dog. The Positive Thinking Dog. So, if you're looking for a book that will teach your dog how to think positively, this is the one. It's about the Positive Dog, Bubba and Mac. They represent the two dogs inside of us. We all have two dogs inside of us. We have a positive dog, we have a negative dog, and they fight all the time.

[00:04:28] Jon Gordon
Who wins the fight? The one you feed the most. So feed that positive dog, and every day. We get to choose what will you feed fear, worry, anxiety and doubt. Or courage, confidence, belief, optimism, hope. You get to choose.

[00:04:46] Seth Pepper
That's beautiful. Could we start with the definition of being positive? There is probably different, like very different definitions. To establish, as far as you mentioned being optimistic, is there a connection between optimism your version and positive?

[00:05:07] Jon Gordon
If I look at positivity and I think of positivity in terms of positive leadership. A positive leader is someone who shares a vision for the road ahead. They have a mission and a purpose that they rally people towards. They also have optimism and belief in their people, and in their future, and what they're creating. So they have a lot of optimism and belief, a lot of resilience, a lot of grit. A positive attitude that helps them overcome negativity. Positive thoughts. They talk to themselves instead of listening to themselves. They don't listen to all those negative thoughts. They're always talking positively, overcoming the negative thoughts that come in. And then they build great relationships with their team. They build great relationships through.

[00:05:56] Jon Gordon
Investing in the person, communicating with them, connecting with them. Committing to them and showing them that they care, we call it the four C's: communication, connection, commitment and caring, and they deal with the negativity. Being positive doesn't mean that everything is always perfect and great. Being positive means you address the negativity and you make those wrongs right. You address them. You are focused on great success because you believe the best is yet to come. You're optimistic. You work your tail off. And you challenge people in order to create a great outcome. We call it 'love tough.' If you know people, care and you care about them, and together you can accomplish something great. You love them, you care about them. They care. Great now I can challenge you and push you. Being positive doesn't mean that you are.

[00:06:54] Jon Gordon
Demanding. It doesn't mean you are demanding. Being positive means you are demanding but not demeaning. I played a lot of pickleball today, so I am a little off mentally myself. For three hours, but yes, so being positive if you are demanding, but you are just not demeaning. And so, as a leader, it includes all of these kind of characteristics. But then, being clear about your goals and aligning them with your values is important. Being positive in the course of your day, for me it means again. You have negativity come your way. You have negative thoughts. You have things that want to bring you down. You have things that are trying to sabotage you. You have people that want to sabotage you. I call them energy vampires. There are naysayers who don't agree with your vision. They don't buy into your vision. They don't want to follow you. You might be their leader and they're working for you, and they don't believe in you and want to follow you. Your positivity must be greater than all the negativity. Your certainty and your belief must be greater than all the doubt.

[00:07:51] Jon Gordon
To me, there are so many elements of positivity. There is belief, optimism, hope, our thoughts, and our perspectives. I think a big part of being positive, as we're talking about this, is me flushing it out of my own mind as we're talking about it. I believe that when you are positive, you are telling yourself a positive story. I believe it's the perspective and the story you are telling. So every one of us is telling ourselves a story. What kind of story are you telling? Is it a drama? Is it a horror story? Is it a documentary or is it an inspirational tale? And so many people today, unfortunately, are living a trauma or a horror story. In those stories, the victim gets knocked out, but in the inspirational tale, that hero that gets knocked down actually gets back up, armed with optimism, belief, and positivity.

[00:08:50] Jon Gordon
They create a better future. They become a hero that impacts others. What story are you telling yourself? And that narrative, that story allows you to have a certain mindset, perspective and belief, and also the actions you will take that allow you to create that future, that result.

[00:09:07] Seth Pepper
Excellent. So on this show, this space that we share, we talk a lot about tools just really because working with warriors heroes. We're going to battle. There is going to be pressure. There is going to be high stakes. What do we do? We know the concept, but what do we do? What does Jon Gordon do? What's your daily rep to be in this space on a regular basis?

[00:09:35] Jon Gordon
The best advice I ever heard was from Doctor James Gill's. He's the only person on the planet to complete six double Ironman triathlons. That's a double Ironman, which means you do an Ironman, a day later, you do another one. And the last time he did it, he was fifty-nine years old. And we should probably share what an Ironman consists of. You run a marathon, you ride a bike for one hundred and twelve miles, and you swim for two point four miles. And the double Iron Man, you do it again the next day. And the last time he did it, he was fifty-nine years old. So he was asked how he did it. He said, "I've learned to talk to myself." Instead of listen to myself, he said, "If I listen."

[00:10:16] Jon Gordon
I hear all the fear, the negativity, the doubt, all the reasons why I can't finish this race. But if I talk to myself, I can feed myself with the words and the encouragement that I need to keep on moving forward. And to me, that's what I've done over the years: talk to myself, feed myself with words and thoughts and beliefs, because negative thoughts are always coming in. And when I am working with an athlete, working with a coach, working with a high performer, I ask him this question: Do your negative thoughts come from you? And they'll say, 'Yes, they're in my head.' And my question is, if you believe those negative thoughts come from you, who would ever choose to have a negative thought? Would you ever choose a negative thought? Would you ever choose a thought that says, 'You don't have it, but you should just give up.' And those thoughts come in. They come in so fast that you believe them. You reinforce them.

[00:11:15] Jon Gordon
You now speak them out loud, and then they do become a part of you. They become a part of your pattern in your speech. They are not the same as the ones who have to be taken out. If I had to choose one, I would choose this one. They become a part of your pattern in your soul, your mind, and in your brain. But you don't have to believe those thoughts because you are not the thoughts you think; you are the thoughts you believe. What thoughts are you agreeing with? That's the key to maintaining a positive mindset. That's the key to mental health. The key to elevating your state of mind is to know that negative thoughts are going to come in. And you are going to have that first thought, and it might be negative, but you have the power of the second thought. And you can speak truth to that lie. You can speak a word of encouragement to that negative thought. And when you do, it's a game changer. You start walking in that truth. You start walking in that power. You are talking about tools here. Here is a simple tool on the left side of a piece of paper: you write down your negative thoughts that come in. I know you have yours; I am mine. Every human being has theirs.

[00:12:15] Jon Gordon
Write them down. Then, on the right side of the piece of paper, write down the words of encouragement that you will say when those negative thoughts come in, and then you start practicing that, and that's been a game changer for me. Another tool is the 'thank you' walk. I coined the term 'thank you walk.' Years ago, my wife threatened to leave me because I was so negative and miserable. She said, 'If you don't change, we're over.' I was thirty-one years old, with two little kids, and I just lost my job.

[00:12:45] Jon Gordon
Didn't know how we were going to pay the bills. I felt like a failure, crumbling from the inside and blaming her for why I have not lived up to my dreams. It was her fault. I had to take ownership. So she threatened to leave and I agreed to change. I read you can't be stressed and thankful at the same time. So I began combining short, choppy sentences into fluid ones. So I began taking these walks of gratitude every single day, so that I didn't feel stressed, so I could feel blessed and feel better. And as I was doing these walks and practicing gratitude, my neighbors thought I was crazy because I was like, "I am thankful for my house. I am thankful I can walk. I am thankful for who I can talk to." I was talking to myself as I was walking. People said they saw me all the time walking around my neighborhood, and I was doing that. But I was literally feeding myself with positivity. I was rewiring my brain. I was creating a fertile mind that was ready for great things to happen. Because the research shows when you do this.

[00:13:42] Jon Gordon
You are flooding your brain and body with these emotions and endorphins that uplift you, rather than the stress hormones that slowly drain you. And doing this day in and day out saw a shift, and I still do it to this day. Now it's a walk of gratitude and a walk of prayer, so I've moved towards prayer, and that has been really essential in elevating my state of mind, creating connection, and transforming who I am as a person. It's been unbelievable. The gratitude walks turning into prayer walks. That's where I've written pretty much every book that I've written thirty three books now. The ideas come on those walks. And I begin to feel the shift. I might start out that walk negative and fearful, anxious, worried, stressed—like so many of us, we all feel that. But then after the walk, I am ready to take on the day. That's good. That's awesome.

[00:14:39] Seth Pepper
So in your books and your material, I notice that you have a lot of evidence, which is amazing. It's great. Can you speak to the power of gratitude? Why is it so significant? Why is it so powerful that people harness it?

[00:14:56] Jon Gordon
Gratitude connects you. Fear, worry, anxiety, stress disconnects you. The root for the Greek word of 'anxious' means to separate and divide. When you are anxious, you feel separate and divided. When you practice gratitude, you create a connection because you now are thankful for it all. And you find and feel this connection to yourself and everything, and to me. Gratitude is actually a form of prayer, and there is a quote that says, 'If all you said was "thank you" as a prayer, that would suffice.' Because you're thankful.

[00:15:36] Jon Gordon
For it all, to the creator who created all, and when you are thankful again, there is a connection. There is not arrogance. There is not something you are missing in your life. You are not lacking, see lacking. Makes you think there is something that is missing, and so you feel disconnected. There is a gap. When you feel grateful, there is a connection, and you are happy for. What you have, and you are grateful for what you have. And, you are no longer missing or longing for something. ;, you are living life from a place of. Of having, of being, and I believe when you are in that state, you have a wholeness to you. A power to you that then draws more things to be thankful for. I call it being a gratitude magnet. The more you practice gratitude, you will become a gratitude. And you will have more things to be grateful for. That's awesome.

[00:16:31] Seth Pepper
You work with the Dodgers, you work with the Heat, you work with a number of other top programs. Let's go with baseball. Baseball has one of the highest failure rates. Are you saying that when someone strikes out, there is a moment of gratitude in that? Or where are we going with the gratitude?

[00:16:49] Jon Gordon
I think in the moment of striking out, you are pissed and you are not happy and you are angry, and that's normal to feel that way. But to get ready for your next at bat. Are you excited about the next opportunity? Are you loving the opportunity? Are you loving the battle? Or are you fearing messing up? Are you worried about striking out again? And they always say. Baseball is a game of failure, Jon. It's such a hard game. It's a game of failure. Because even if you're a hall of famer, you're still failing two out of three times, right? Two out of three times, so you are a hall of famer and you are still failing a lot. So it's a game of failure, and I say no.

[00:17:30] Jon Gordon
When I go speak to these teams, I tell them it's not a game of failure, guys; it's a game of opportunity. Because every at bat is an opportunity to make the next one great, it doesn't matter what happened on the last one. You got a hit, or you struck out. You are moving to that next at bat. With the opportunity to make the next one great, so whether you had a hit or whether you struck out, you are in the same position at the next at bat. It's your mindset that determines how you approach challenges and setbacks. If you're always looking for shortcuts, you'll never be able to do anything meaningful. The key is to focus on the present moment, not on the past or future. Focus on the current task at hand. It's your mindset that will determine how you perform at the next at bat. Do you want to be thinking about the last at bat? Or where will your power be greatest? Where will your mind be the strongest? Where will you have the most success when you are focusing on the present moment, not in the last at bat? Even if you had a home run, you still don't want to focus on the last at bat. You want to focus on this one and be in the moment. I always ask athletes.

[00:18:27] Jon Gordon
When are your best when you are thinking or not thinking? Thinking or not thinking. And they always say, "What I'm not thinking." So why do we want to think more? We don't see ball, hit ball. See ball, hit ball. Be in the moment. It's all about you and the ball. Don't think about yesterday. Don't think about tomorrow. Don't think about your contract. Don't think about what happens if you don't get a hit. You just focus on loving the battle. Loving playing, loving the moment, and it's you in the ball. And when you focus on that, you'll perform at a higher level. And it's easier said than done, but that's the mindset that we have to have. So being positive doesn't mean that I am just going to stay positive, even though I just struck out. It's striking out and going, next at bat, let's go preparation excitement. Let's see if you can get me again. Let's go.

[00:19:25] Jon Gordon
It's love in the battle. You got me last time. I'm gonna win the next one. It's that positive expectation. Positive anticipation, that's what you want to have as a warrior, as an athlete, as a high performer. Again, you might have made a mistake, but it's the next one that matters.

[00:19:42] Seth Pepper
So are you seeing that as a difference? Let's say someone that's in the major leagues as a hitter versus a slugger. Have you seen a difference between the great ones and a player who is making a lot of money?

[00:19:57] Jon Gordon
I am not sure about that, but you talk to a Paul Goldschmidt.

[00:20:02] Jon Gordon
Paul Goldschmidt did not measure his at bats based on 'did I get a hit?' He measured his at bats based on whether he made great contact, whether it was a great swing, whether he had a great at bat, and whether he made the pitcher work for it. Because you could actually have a bad swing.

[00:20:24] Jon Gordon
A bad at bat and get a hit. That's why Jon Madden said, "Winning is a great deodorant. It covers up what's wrong with your team." So you might have success, but you did everything wrong. And there are times you do everything right, but you still get it out. If he would make great contact and hit the ball really hard, and it still went to an opposing player, it was still a success. And I think that should be our measuring stick. It's not about the outcome; it's always about the process. And how you played, and how you focused, and how you showed up. What was your mindset in that moment? Was it confidence? Was it courageous? Was it connected to the moment, or were you thinking a lot, fearful, worried and anxious? And then they just go like this, and you're like, "Oh my God, this is so weird." Yeah. Right? And I think if you focus on the outcome all the time when the outcome is great, you're going to be happy. When it's not great, you're going to be miserable.

[00:21:23] Jon Gordon
Instead of focusing on your mindset to attack each moment, research is clear on this. People and teams who feel like they're defending something don't do very well. But people and teams who feel like they're attacking a new opportunity do great. They perform better. You don't have to defend your last at bat. You don't have to defend your status, your position, your past success. It's about attacking a new option. Right here, right now. And when you attack new opportunities, you create more success in the future.

[00:21:59] Seth Pepper
Excellent. So earlier you were talking about prayer. I like to talk a lot about the flow state, the zone, being present. You said in the moment. Do you think there's a connection between some level of faith, letting go and letting God or team first, where you stop thinking and allow something greater than yourself take over?

[00:22:24] Jon Gordon
The Zone state is the ultimate connected state. When you feel connected, and I believe it's because of love, I believe the universe was created with love and love was the intention. And we are the intention of a creator who loves us. And when we are one and connected with that love and feel that connection, now we have greater clarity, and when you have greater clarity, you've been in the zone; I have as well. It's the best feeling in the world. It's bliss. You feel one with everything in the universe; there is no separation. Time slows down; you know what to do next.

[00:23:21] Jon Gordon
There is thought, but you are not thinking. It's a greater thought, and I really believe so many athletes have. Have a strong faith, a strong sense. I am not talking about religion, a strong faith and a sense of the supernatural. Because you've been in those moments where you knew you weren't strong enough, you knew that success you had there was something greater carrying you. Pushing you, moving you towards that finish line, towards the end of the game. Making that shot, making that play. I had a moment where I experienced that, and I heard the voice, "Get up." Get up, and I fell down. And I got up, and I watched the tape. And I thought it was a long time. It was a split second, like that, where I got knocked down and got right back up. Went down and scored the game tying goal, then won it overtime. I had that spiritual experience. And I'll never forget. It was one of the greatest moments and greatest.

[00:24:20] Jon Gordon
Feelings of my life, it's that connected experience. But here is what I think: this is going to rock a lot of people's worlds, and their minds are going to be blown. I don't believe the zone state is a peak experience state. I believe it's actually meant to be our normal state. I believe we're actually meant to live in a connected state with our creator. That was the intention, I believe. Clutter. And the feeling of anxiety, worry, and disconnection is actually the abnormal state. We're meant to be one and feel whole, but everything in life actually disconnects us. And then we feel like we are not being heard. We feel divided. We feel weak, and then we feel fearful and anxious. So we need to get into the ego, but the ego actually arises because we feel so disconnected.

[00:25:19] Jon Gordon
When you are connected, there is actually not an ego. There is peace and there is joy and there is humility. But, then there is a greater love and power because you are coming from this place of connection and wholeness. It's like you take a plug, you plug your computer in, you plug your phone in; it gains power. You lose power; there is a disconnection that happens, And then it starts to run out of power and becomes weak and have weak energy. It's the same thing with us. The more disconnected we live, we then live with this weak energy and this feeling of Powerlessness, and that's why we get people that have heart attacks. Chronic fear. Chronic exhaustion, disconnection. They say, "Well, I work hard." It's not because you are working hard. Because, there are days, and there are times in your life where you work really hard and you are energized by it. So it's not that; it's the fact that you disconnected.

[00:26:18] Jon Gordon
But then you come from a place of connection, oneness, wholeness. Your mindset is elevated. You are feeling great. You feel the love. You feel the connection. You can go for hours. You can go for days and you don't get tired. So that's what I am talking about. So the zone state and the i was about to say, peak state, The zone state and our normal state feels like a peak experience. But I think we're meant to live there more often. And I do believe the more you pray. The more you pray, you actually elevate your state of mind and you create the connection. Look at my hands. You have God, you can call it your higher power, and then you have you. When there is a disconnection, what happens? That's where the negative thoughts come in: the fear, the worry, the anxiety and doubt comes through there. The hole that we have in our soul, the wounds of our past is what a disconnection a separation.

[00:27:18] Jon Gordon
You heal, you become connected. Can those thoughts be negative? They don't come in. That's when you are at that zone state. So how do you get there?

[00:27:32] Seth Pepper
So simple

[00:27:35] Jon Gordon
Yes. You were created for connection, and when you pray, you connect with the divine. With your creator, but I can prove this when people have mental health disorders. They all report feelings of isolation, disconnection, and separation. I told you about the root to the Greek word of 'anxious' means to separate and divide. When someone experiences trauma in their life, there is a neurological separation that happens in the brain. We call it 'broken brain.' Schizophrenia means split mind. Bipolar: two poles. Everything is connected. Everything is connected.

[00:28:17] Jon Gordon
And they even use the term "psychic break." There is a break that happens psychologically, and a disconnection in our soul, mind, and brain. That implies that wholeness is the intention, and the more we seek and move towards wholeness. In connection, we move towards healing, and that's when you become more powerful and strong. And so, relational psychology says you heal in a loving relationship. Can you heal with a stranger?

[00:28:49] Jon Gordon
We were strangers, but we're not anymore. Now there is a connection. The minute there is a connection, we can heal. But if we're just strangers, you can't heal.

[00:28:59] Jon Gordon
But now there is a connection, and we're no longer strangers and healing begins to take place. If God is a stranger, can He heal you? No. It's not meant to be some impersonal higher power; it's actually a personal God.

[00:29:16] Jon Gordon
That loves and created you because I truly believe that, and when you become one with that love and that connection. That's when the healing takes place, and we see so many people living disconnected in this world, and it's why they are struggling. In this world, but then that would make you ask, and I know this all right, Jon Moore. That's the case. Then why are so many Christians who believe in God and have faith struggling with their mental health and their mindsets and sin, and they do all these things? I wrote about this in the one truth. There is the spirit, there is the soul, and there is the flesh. And the soul is the integrator between the flesh and the spirit, and flesh are at odds with each other. And Romans eight five six actually says, "A mind governed by the flesh leads to death." A mind given by the spirit leads to life and peace.

[00:30:15] Jon Gordon
What is the soul being governed by? The flesh and the things of this world, and the dysfunction and the wounds of the past, Or the spirit and life and peace that comes from being connected to the spirit. And you have a choice. And. So t here is a lot of Christians that maybe they've been baptized, and they would say, "I've been saved," but their soul still needs healing. And I would say most people on the planet their soul still needs healing, and this soul must bathe in a spirit. For the healing to take place. Here is a great analogy :. You take a cucumber and you put it in pickle juice and pull it out real quick. Is that transformed? No. It must bathe in the pickle juice to be transformed. Guess what? That submerging and pulling out is baptism ;. It's not meant to be a one time event. You are actually meant to bathe in the pickle juice through the power of prayer, and as I pray and I surrender and I trust.

[00:31:13] Jon Gordon
And I bathe in that spirit, and literally you can feel that connection and oneness as you pray and connect. Research is showing more and more the different parts of the brain that actually stop being active. During times of prayer and meditation, you experience this selflessness, and you experience this connection to something greater. When you are in those states, I would say that's the state of being connected to your creator in oneness. When that's happening, that's when the healing is taking place.

[00:31:44] Jon Gordon
And also with other people, connection to other people, and that's why when you have addiction programs, you have people who move towards community and connection, and these sorts of experiences. There is some self-love that starts to happen that helps with connection, but the self-love will not heal the hole that you have in yourself. And having great relationships helps you heal, but it will still not heal the hole in your soul. Being connected to your Creator is what does that through love and forgiveness. So there is a love and a forgiveness that takes place of all the things you've done wrong, of all the wounds that you carry, of all the shame that you carry, of all the mistakes that you made. And you literally let it go. And I call it forgive fast instead of holding on to that hot coal. You want to throw it at someone? You are angry, they wronged you, they hurt you, and you want to get angry and you want revenge and you want to get back at them. You are holding on to it, but you are being burned in the process.

[00:32:43] Jon Gordon
But imagine you forgive fast and you release it. The minute you do, you start growing in here. And as you do through forgiveness and through love, that's where the healing begins to take place. It's interesting because when I knew I wanted to be a writer, I couldn't write. I want to write and I couldn't write. And I went up to go visit my biological father who left when I was a year old, and I brought my daughter with me.

[00:33:14] Jon Gordon
And I forgave him for not being there, for what I felt like was an abandonment. And I told him that I was not going to hold on to that anymore. I was going to let it go. I was releasing him. You see, I wasn't doing it for him then. I was doing it for me so that I could heal, because I knew I was holding on to it, and it's holding me back. So, I forgave him. I didn't realize this until recently. But that was when I actually started writing books. After that, I came back and started writing right away. All thirty-three books that I've written since came after I chose to forgive. The faster you forgive, the sooner you start writing. And I share this story because there is someone listening right now. You need to forgive fast. Because I wish I would have forgiven faster. Man, I wasted so much time. I was thirty-two, thirty-three. Imagine if I.

[00:34:13] Jon Gordon
I could have started growing a whole lot faster and achieved a lot more. I had to wait to start growing. So you forgive fast and you will start growing. And by the way, this works really good in traffic. Someone cut you off, just release it right away. Don't hold on to it. The minute you forgive, in that moment, guess what? You are going on with your day, and you are creating your future instead of holding on. And one other thing I want to say about this, I know I've been talking a lot.

[00:34:44] Jon Gordon
The thing about this forgiveness is so important, because whatever you are holding on to, whoever wronged you, the bitterness you carry and the anger you carried towards them and the wrongs they've done, they are real. When you don't forgive, you are still connected to that person. There is a soul tie that happens. So you are still connected to this person who wronged you. Wouldn't you want to let them go and release them, so you no longer have a connection to them? When you forgive them, you release that soul tie, and now you are free to create your life. You know, I think it's important to mention that in the past few years, there has been some changes in the way we do things here. The reason you should forgive is so you can let them go and release them from being this weight that you are carrying. I remember this woman said she lost one hundred and ninety five pounds. It's a lot of weight. She says, "Yeah, that's how much my ex-boyfriend weighed when I forgave him for what he did in our relationship." Forgiveness is the ultimate weight loss.

[00:35:41] Jon Gordon
You release, you let it go, and you start to live light and live free. Excellent.

[00:35:49] Seth Pepper
So let's talk about simple tools again.

[00:35:52] Jon Gordon
We went deep there. You went deep.

[00:35:54] Seth Pepper
We're going to go in the same direction.

[00:35:56] Jon Gordon
Here is what I love: I love going deep and I love giving practical tools. That's the thing; we're both about tools, but you have to understand the essence behind all of this, because there are a lot of people that just give tools. What happens when the tools no longer work? What happens when the mindset technique doesn't work because you are focused on the technique, not understanding how thoughts actually work, how the mind works, how the soul works? Once you understand that, everything changes. And I hope we get into the subconscious mind because everyone talks about the subconscious and I want to ask you where you think it actually is.

[00:36:34] Seth Pepper
Oh! Pop quiz.

[00:36:39] Seth Pepper
Before that, I just had a question as far as prayer. Someone that didn't grow up in a household where they were going to church on a regular basis or studying the Bible. What is prayer? You mentioned meditation. What if someone's out there and they're like, okay, I want to give this a chance, and I don't mind doing it on a regular day. I take walks. Why can't I do what he's talking about?

[00:37:05] Jon Gordon
One, I was a Buddhist meditator for a while. I was a new age seeker, a Buddhist meditation in my twenties. Seeking healing, not sure how I was finding it. But seeking it, and I would do all these techniques and strategies, and it worked for a little bit. Until it didn't, because the wounds were still there. The whole of my soul still needed to be healed, and you can do all these techniques, but I know it still doesn't heal the whole.

[00:37:38] Jon Gordon
I am a huge fan of meditation because I know as you begin that practice. It allows you to be still and quiet, and you get a whole lot less thoughts coming into your mind when you start to tame your mind. This practice, and I love that because if you have a lot of clutter in your mind, it's hard to create clarity or make decisions. If you're not sure about the direction of your life, then this is a good time to take a step back and reflect on what you want from life. And so meditation removes a lot of the dots in your mind, so you have less clutter. More clarity. So it's a great tool for your mind and for the connection to begin to take place. And so I am a big fan of it. If you are comfortable with that, and you start this practice of meditation whether it's a walking meditation. Whether it's a Buddhist meditation.

[00:38:36] Jon Gordon
Whether you focus on a number like one, whether you focus on one word in your meditation like love. A lot of times I'll meditate and I'll say "love." Other times I'll say "Jesus." At thirty-five, I became a follower of Jesus. So, I did not know anything about the Bible. I was not religious at all. I grew up with no religion. We never went to temple. We never went to church, so when I talk about all this, I talk about it really from a very spiritual and a metaphysical. Place of healing and forgiveness and love. And restoration and the healing of the soul. I really become an expert in the healing of the soul. I was just talking to someone yesterday, and they were telling me this issue of people pleasing, and I said, "Well, of course you are doing that because you don't feel worthy. " And. So you are trying to please them because it makes you feel good in the moment, But you are really doing it because that's how you get your accolades and your self-worth. But deep down, you don't feel worthy yourself.

[00:39:35] Jon Gordon
They were like, "Are you a soul doctor?" So I've been called at times because God gives me hits in those moments of just seeing what that person's wound is and knowing where the healing is necessary and where it needs to take place. So if someone is not of a religious practice, that's okay and there is no judgment. My thing is just focus on connecting and believing in something greater than yourself. You believe in a higher power. You believe that there is a God who created everything. And is it by accident? Because if it's by accident, guess what Seth, you're an accident. And so am I. Are you an accident? I am not. But if everything is randomness and there is no creator. And this all just random chance. There were accidents. You can't have it both ways. It's one or the other. And once you realize that this not an accident, there's intention, there's intention, there's purpose, there's intentionality, there's meaning behind the words, and the outcome is not accidental. There's intention, there's purpose.

[00:40:33] Jon Gordon
You don't have to like religion, but you can believe in a God that created this universe and that we are part of that creation. We were never meant to live in an independent relationship. It was meant to be a dependent relationship. That's the whole point. You actually were meant to live connected to your creator in oneness, not separateness, so that you can give everything to this world and be replenished with power and peace, and joy, and confidence, and love in that connection. Just like plugging your phone and your computer and charging up your car. Everything needs to be charged. Guess what? You need to be charged up as well. So that's what I am trying to say here. So I would say you start every day. You can start with meditation, you can start with gratitude like I do, or you can do what I do. I start with praise. Actually, I have an acronym: prayer (P R A Y E R). I'll share it now if you want to hear it. Yes, I think this is helpful to help people pray. You start by praising.

[00:41:33] Jon Gordon
The Creator. God, you are amazing. This universe you created is pretty unbelievable. The way it all works. At night, the insects come out, and somehow the birds come out as well at that exact time. Everything just seems to work. If we were not in the position that we're in, in space. If our Earth was just tilted a little bit more on its axis, there'd be no life. If we were Father from the son, there'd be no life; like everything is just too perfect, so you praise God for the creation. You praise God for who God is as the Creator, and then there is a repentance. Is the R where you repent. You repent for your sins, your pride, your ego—all the things you've done wrong. Why you got to clear out that sludge that you have in your pipeline. All that stuff you are holding on to, my Buddhist energy healer that I went to years ago. He called it soul pain.

[00:42:32] Jon Gordon
He goes, Christians call it sin. I call it soul pain because it's heavy, vibrational energy, and you are carrying it and it's heavy and it weighs you down. So repenting is letting go of the heavy energy that you carry. Just let it go. Then there is the A in prayer: ask, ask for what you want, ask. Believe that there is a God who wants to actually give it. And so you ask. I ask for confidence, I ask for wisdom, I ask for guidance, I ask for influence. Affluence to impact to make a difference. I ask for people who I'm meant to help. I ask for people who I'm meant to partner with. I just ask. I ask, and I believe that if I ask, if I am meant to have it, I will. And if I am not, I won't. So I am not being bound to it. I am not angry if I don't get it. But I am going to ask, and then I yield. This is the big part right here: yield. This surrender. This is the game. You don't do anything else.

[00:43:31] Jon Gordon
But you just every day surrender control and surrender the outcome, and you stop trying to be the creator of the universe yourself. You stop trying to be God because you make a pretty crappy God, and I make a pretty crappy God. When we try to be God, it doesn't go well. So we have to realize there is a God and it's not us. Here is the challenge that most people have. They don't trust in God, so they try to be God, and that separates them from God. That's where the disconnection happens. High performers, people who are type A, always in control. They don't really trust in God, so they have to be God. It separates them from God, and then they carry the burden of this world and the universe. We were never meant to carry that burden, but that's why people get so stressed and exhausted.

[00:44:29] Jon Gordon
Miserable because they are carrying the burden, trying to be the creator. And this is where surrender comes in. This is why there's a serenity prayer. In AI, so many of this makes so much sense because when you surrender, you let it go. And you trust in a bigger plan, in a bigger God, in a Creator. When you do that, you are now free to go live your life and do what you are meant to do and give your best. And you let God do the rest. Surrender is really important, and my surrender looks like God. I give it all to you guys.

[00:45:00] Jon Gordon
I let it go. I let go my pride and my ego. God, make me a vessel for what you want to see in this world. Make me an instrument of your peace and your joy. Use me to impact that. Use me to. To help others, God. Make me a conduit for your miracles. Make me an instrument for the positive energy. And the love and the hope you want to see in this world and in others, just use me for that. And I'll surrender, God. You are my speaker bureau. Have me go where you want me to go. And be. Where you want me to be, help me ultimately become what you want me to be. I let it all go, all the control. All of it, just use me in that way, and so now I am surrendering. And I am trusting, and I am just letting it all go. And when I do that, you can literally feel. The spirit starts to move through you because you are getting rid of all of that heavy energy that you are holding on to, and now you become a conduit instead of a resistor. You become a conductor.

[00:45:58] Jon Gordon
Resistors hold on to its electrons, so a resistor has limited power. A conductor freely gives and receives its electrons, so the power comes from the current that moves through it. And so we want to be conductors, not resistors. So I surrender—that's key. So that's the yield part, and then there is the E part of prayer, which is expecting great things to happen. You would call that manifesting. I expect great things to happen. I trust in your plan for my life, and I'll often say, "God, I expect great things." I trust in your plan. Send me a miracle. I am ready for a miracle, God. Send me a miracle. I am ready for a miracle. I expect amazing things are happening, so now I am expecting. But the difference between manifesting and this is when you are manifesting, it's like I did this. I manifested this. It's not about you manifesting anything in your connection and oneness with the creator. The spirit moved through you to manifest what was meant to happen. To create ultimately.

[00:46:57] Jon Gordon
Your highest good and the highest good that you are meant to serve and attract. I don't believe you manifest a car or a house. I believe that in your oneness and your connection, you go and do what you are called to do, and then it comes back to you tenfold, as you are serving the law of reciprocity. That happens so often. And so there is this expectation of expecting, and the last one is receive. Or receive so prayer, you receive, all that God has for you. You receive the blessing, you receive the gifts, and so I'll walk and I am like, "I received all the." All the people I am meant to help, I receive. All the people that are going to read my books and benefit from them, I'll say that I receive. I received the teams I meant to go work with, so you just go live open and surrendering and trusting. And you are receiving, and it's a really powerful way to live. You become a conduit instead of something and someone that's holding on to everything. You're letting go, and now you allow.

[00:47:56] Jon Gordon
That incredible abundance in this world because it's a big universe. And there is a lot of energy in this universe. You allow it to move for you. Why do we expect so little and think we are so powerless when really we are meant to live with such power to make a greater impact in this world? Amazing

[00:48:16] Seth Pepper
So is there a connection to this, the state and what we were just talking about as far as the flow and being in the zone?

[00:48:25] Jon Gordon
I definitely think so. I definitely think that when you are in the moment and you are able to surrender in that moment, truly trust and receive, and experience that oneness, it will allow you to experience that state more often. But I also believe that an athlete who believes this and knows this, who also might identify themselves as a Christian, still has those moments when they're looking at the scoreboard and looking at the fans.

[00:48:56] Jon Gordon
They're wondering what's going to happen on social media and ESPN if it doesn't go well. They're still going to have this feeling of looking outside and thinking too much and not being in that moment. That happens all the time. So you can pray all night, but in that moment, you are stuck and disconnected. That's what happens. There is an ebb and flow, and the key is to know that. So often in those moments, we're just believing a lie. We're believing that something outside of us can impact how we feel. So we look outside instead of inside, and the key is to be inside out. The more we can truly just focus on the inside, the soul, the spirit, the more we can understand each other and connect with people. The problem is, when I say 'soul,' some people think it's like a religious thing. But it's not about religion. It's about the essence of who we are, the core of our being. So when we focus on that, we can connect more deeply with others and with ourselves.

[00:49:52] Seth Pepper
You talk a lot in your books about energy vampires. Real quick, my mom was a clinically depressed person, and that's what I believe created this. It sparked a curiosity about the difference between myself and her. It all serves a purpose, but definitely an energy vampire. My wife is a physical therapist and she's great at it. I love the mind; she's of the body in our sort of focus, and she worked on my mom before my mom passed away. She said, 'She came back crying.' And she said, 'Because she's very sensitive.' Yeah, she said, 'She's an energy vampire.' And so she would come feel it. And she said, 'This will wipe me out for the rest of the week, just being around your mother.' So speak to that a little bit of like energy vampires, you know, having that contrast.

[00:50:51] Seth Pepper
Maybe even people in their own life of having close loved ones that are cynics. And don't believe, And you know, things like that, that we have to deal with.

[00:51:01] Jon Gordon
When you walk into a dark room. What happens when you turn on the light? You suddenly can see, and the darkness dissolves. And now you see the light. I really believe with your wife, if she would have known this. And even in the past, if she would have showed up saying," My love is going to be so much greater." That any form of negativity she brings, that love would be so much more powerful. Then that heavy, dark energy and negative energy. My father was a New York City police officer. And he was that energy vampire and negative. Like, my dad was like, "Can't believe people actually pay you to speak." When you were a kid, we paid you to shut up. These are the things he would say to me. He was always so negative, but I just kept coming back. Positive belief.

[00:51:50] Jon Gordon
And I believe that when we're around energy vampires and negative people, they're actually our greatest test. And they are meant to help us grow stronger and become wiser and better. If you never were exposed to germs, would you develop a strong immune system? You have to be exposed to the germs in order to develop an immune system. You have to be exposed to the negative people and the energy vampires in order to become resilient and stronger in the process. Adversity is our partner in growth. Energy vampires help us grow. People say, "get rid of energy vampires." Yes, on your team organization, if they are sabotaging the team. You should let them go, But I believe you give them every possible chance to get on the bus to be a positive influence. To realize that they actually need healing and that they can actually become the best version of themselves, they can tell themselves a positive story, they can shift their energy. I've seen it so many people have transformed after reading " T, he Energy B us " and the work that we do in workshops and trainings and so forth.

[00:52:49] Jon Gordon
So I believe there is an opportunity for everyone to get better. But again, you are in the workplace. Someone's sabotaging the team. They're unwilling to change. You got to let them go. When you deal with someone like your mom, or I had this one guy say, 'Hey, my wife's an energy vampire; kicking her off the bus is not an option.' What do I do? And in the case of your mom, you just respond with love, and you just keep sharing love as you did and as your wife did.

[00:53:19] Jon Gordon
But your wife has to know that no matter what, if she ever experiences that again, she is more powerful than any negativity that comes. Or what if we believe that person could affect us, they will. It's almost like if you look at home court advantage in sports, everyone says there is home court advantage. But what are we measuring? We're measuring the belief that there actually is home court advantage. And because guys actually believe it, they actually experience it, but if you are like the player that said to me, "I don't believe in home court advantage." I just go do what I do and play my game. It's a lie. Do you believe it's a lie? Then it's not going to affect you. When we're measuring home court advantage, we're measuring the belief in home court advantage. When we are measuring how an energy vampire or someone negative could affect an organization, a team. They can if we believe they can, and if we truly know that we are more powerful than them, then they won't.

[00:54:18] Jon Gordon
Does that make sense? Absolutely, and so it's about approaching that from a place of love and confidence. And true power realizing that person's coming from a place of disconnection. You are coming from a place of wholeness and connection. And the more whole you are, the more connected you are, the more you share love and light. Their darkness has no power over you. Excellent. Did that answer your question? Absolutely. I don't know if I fully answered your question on that.

[00:54:44] Seth Pepper
So I want to be respectful of your time. Quick question. It can be quick. You work with these top programs and then you also work with other programs as well. We're talking about athletics. No names. You walk into the building, you feel the culture. Can you tell it's a winning culture?

[00:55:05] Jon Gordon
You can tell if they're connected. You can tell if they're committed. You can tell if they're positive or negative. You can tell if there is dysfunction. You can tell if they're on the right track. You get a sense, you get a feeling. There are times that I am wrong. There have been some teams when I go there during training camp, you had a great vibe, great energy, but then they experience a challenge and some sort of adversity. It reveals that they weren't really that strong and there was a break there. Then you see other teams where they start out slow, but they stay together, and they stay strong together.

[00:55:46] Jon Gordon
And then you watch them grow in the course of the year. That's why it's so important for leaders and coaches to be intentional with their team building process. It's an ongoing effort. It's not a one-and-done thing. It's an everyday thing. Leadership and great teamwork is built in increments. So it's like every day we're creating a conversation. Every day we're having conversations about who we are, what we're doing, who do we want to become. The relationships that we're building, and so it's not a one-day thing; it's an everyday thing. And I can tell when I work with these companies and organizations how strong their culture is. You get a sense immediately.

[00:56:28] Seth Pepper
It's that energy.

[00:56:29] Jon Gordon
You feel it. You just feel it. Like when I spoke to the Jaguars this year during training camp, I asked, How connected are you as a team? Four, five guys were saying, I felt that I knew it by the end of the season. Man, these guys were connected. There was a bond. They had this unbelievable strength as a team, and they worked on that. And I remember after I asked that question, Coach looked at me. I looked at him. One of the player engagement guys came up to me, goes, "We got some work to do." I am like, "Oh yeah, you do." Because if you are still a four or five during the season, it's not going to be a good season. And I even told them, guys.

[00:57:11] Jon Gordon
These are the seven commitments of a great team. You live these seven commitments, it's going to be a great season. You don't, you're going to look back and say, 'That's why we had a crappy season.' You get to choose what kind of team you want to be. And I challenged them. And I just had Liam Cohen on my podcast, and we just met in person, and we talked about that meeting. He said, 'No, that was good. That was great when you came in and did that and said that.' He's like, 'Man, that was awesome because we weren't. We weren't a connected team.' And I can tell. Worked with Dave Roberts years ago with the Dodgers when he first got the job. That's all we talked about. Dave, you got to go connect with these guys. Got to build those relationships and connections. He did that so well and has done that extremely well over the years, and he builds that connected culture. And then you don't really have any issues with guys. You don't hear any negativity in the media about this guy who's disgruntled, that person's not happy, is unhappy. You see a team that

[00:58:10] Jon Gordon
Is experiencing the fruit of a great culture. I always say, you know, if you want to have a good team and have good performance, if you want to have good fruit, you have to invest in the root. Ignore the root, focus on the fruit, and what happens? The tree dies. But if you are investing in that root, you're going to get more growth. And it's the same thing at home with our kids. We invest our time with them, our relationship with them, the culture of our home. Really building a great culture at home, and we make that a priority over time. You are going to see these kids thrive because they came from a great root system that will produce great fruit in their lives. And too many people today are so focused on the fruit and the numbers and the outcomes and the likes and social media followers that they're not investing in the root. And what happens is when the tree dies, they don't know where to turn, where to go, and guess what? They crumble.

[00:59:11] Seth Pepper
So true. I've been there. Circling back to your question, the subconscious mind I always call it the supercomputer. It's the thing that drives the car without you thinking about it. That's my simple definition. What's that? Where is it? It's below the surface, in a sense. Like the metaphor that I use, an iceberg; it's underneath the water.

[00:59:38] Jon Gordon
It's all around us.

[00:59:39] Seth Pepper
But I want to hear your definition.

[00:59:41] Jon Gordon
Where is it? Where is the subconscious mind? Is it in our brain? Where is it? What is the subconscious? Subconscious is our soul. You have a subconscious because you have a soul, and the soul is your spiritual DNA. It's the expression of you. It's your sense of self. Interestingly enough, the soul and the ego are actually one of the same. You have an ego because you have a soul because you have a sense of self. If you just were spirit and no soul, you'd just be floating around, but there'd be no sense of identity or self. So the soul actually gives you a sense of self. But the soul is like the spiritual energetic expression of you. And when you die, your body turns to dust. Your subconscious is not part of the actual physical body that turns to dust. Your subconscious is the actual soul that is an energy field.

[01:00:38] Jon Gordon
Warehousing everything, the brain is literally where it's activated, but there's no memory or thought in the brain. Thoughts do not exist in the brain. I've asked neuroscientists; no one has ever found a thought in the brain. It's the thought that comes from a soul, spiritual level. That's why thoughts pop in. And you can't find an actual thought in a brain because thought doesn't have any physical substance to it. It's a pattern. It's an energy to it, and so when you have this thought that's happening, that's from your soul, but it's brought to life through the brain activating. Just like we get make sense of this world through our brain firing synapses. And then we're creating this reality that we're living in. So the soul is actually expressing itself in this reality. And so the soul actually creates and carries your life, and also the patterns of thought, beliefs, and perspectives.

[01:01:37] Jon Gordon
Memories, I don't think memories are in the brain. Memories are in your soul. And it uses the brain to actually crystallize it and make it real, like the Matrix. In this moment, but your soul is going around, and when you die, your soul still is alive and still part of this existence. Whatever it is, like there is a greater existence that the soul is part of, and I believe the soul is eternal. The soul is an eternal soul. And that's why Jesus talked about taking care of your soul because He knew this world was temporary. We all die, but then the soul lives on. And so it's about nurturing the soul. So are you living with the soul and the spirit, or the flesh, and you see that play out in this world every single day.

[01:02:26] Seth Pepper
So last question, just call it the pep talk. Which take on the last name of? But what would be, and you live a life. Giving people tools and lessons and guidance, but in this moment, what would you share as being your pep talk that would reach any listener out there?

[01:02:45] Jon Gordon
I would say that expect challenges because you are going to face them. Expect adversity. Expect rejection. Expect betrayal. Expect people to hurt you, but know that when you respond with love, when you respond with belief and optimism and hope, and you don't allow their opinion and their life and their wrongdoing to affect you, that if you truly live from the inside out of who you want to be and what you want to create, that is living with power. That is living with intention. And I would say you are not meant to go through life worried, chronically stressed, fearful and anxious all the time. So many people are living that way and it's become normalized.

[01:03:32] Jon Gordon
Just because you see so many people doing it, doesn't mean that you are meant to live that way. You are meant to live. With confidence, with courage, with peace, with joy and power. And the more you do this work. The more you focus on this connection and having this power to live this life, and it all starts in the mind. It really does, and having the right mindset and choosing love instead of fear. And I am a warrior. You are a warrior, like loving the battle. Man, life is hard and is challenging, but you see it as a battle, and you love the battle, and you love the challenge, and you love the adversity. And you love everything it teaches you. You're going to be so much stronger and so much more powerful. And that's how you take on this world. That's how you overcome. It's two different mindsets. : one allows the world to create them. ; one believes they have the power to create this world. And you're meant to go live and create this world your life Why? For yourself? It's not just for you part of it but.

[01:04:32] Jon Gordon
It's so that you could actually impact the lives of others. God doesn't give us power for ourselves. He gives us power so we'll actually use it for good and impact others. We see it in movies. We see it in all the heroic stories of Superman and Batman and all the incredible Marvel movies. That's where it all actually goes to that archetype, it all goes to that fabric and framework that actually is in our soul, and why we resonated with so much. It's a battle of good versus evil. Evil wants to destroy you and bring you down. There is a God who loves you and wants you to actually overcome evil with good and win the fight, and gives you the tools to do it. Guess what? Use the tools. Go out there with power and peace, and go win the battle. And I believe that's what we're meant to do. And I think when you see the challenge in this world, and you see all the stuff that's happening. You can't look at it and believe, "Oh, that's just out there and I can't do anything about it." You have to know deep down that you can do something.

[01:05:32] Jon Gordon
You can't do everything, but you can do something. So do that today and make positive progress.

[01:05:38] Seth Pepper
Amazing, I can't even imagine you without a smile. When you were negative, were you still smiling?

[01:05:44] Jon Gordon
I probably still smiled, but not as much. You have such a. I definitely was depressed. I definitely had depression and anxiety, but it's because I was so disconnected. I had no faith, I had no belief. I was my own god. My identity was tied into success. And then when I lost my job, almost lost my house, now my identity. Who am I? Lost my business. I'm nobody. How can I become something? What am I here to do? So I cried out, "I said, God, why am I here?" I know I'm here for a reason. What am I here to do? And literally, writing and speaking came to me in that moment. I said, "All right, that's what I'm going to do for the rest of my life." And I said a prayer, "God provide for me and I'll do your work."

[01:06:30] Jon Gordon
Has it been easy? I get my ass kicked a lot. It is not easy, but I know I am here to fight for the good. We were all here to fight for the good, and I'll finish with this. Why do we have a competitive spirit? You ever think about it? People want to win, but why. You are going to die, so what's the point of winning? What does it matter if you win a championship when you die? You'll be dead. Your kids can talk about it, but you'll be dead. So why do we compete? We compete because life is a battle, and we have to learn how to compete to become people who actually fight for the good. And so, as you learn how to compete in the scoreboard, in your times whether you are a swimmer or an athlete, you learn how to compete in debates and musical performances. You learn how to compete, so you become someone who has to compete in this world. Because what are we competing against? We are competing against evil, and all you have to do is read the news.

[01:07:27] Jon Gordon
You'll see a lot of evil out there. There is evil in this world, and we have to become stronger than the evil that we're facing. We have to become stronger than the adversity that comes our way. And as we do, because we competed, because we became stronger, we're now someone who actually can win the fight. And Tim Tebow is a great example of that. People give him a hard time. I know Tim. Tim is fighting sex trafficking around the world. Here is a guy who was the most competitive guy on the football field, and I played pickleball against him. And he's very competitive. We played singles, and he's really competitive. And here is a guy that I just said, 'Wow, most competitive person I've ever met.' And now I am watching him testify in front of the government as part of fighting sex trafficking. And I am watching him do what he's doing, and I am like, 'Man, that's why he's so competitive.' Because he needed to be someone who could actually get it done. Because if you don't do that, you will never be able to get people to follow you.

[01:08:27] Jon Gordon
And he wasn't strong; he could never win the fight. That was beautiful.

[01:08:32] Seth Pepper
That's what we're here for. Thank you, Jon. Thanks for having me. Yeah, This has been appreciate mind blowing, and thank you. Yeah Um promotion. How can people get connected to you? I know that I've enjoyed your classic book, The Energy Boss, and a number of others. You have thirty three books out.

[01:08:50] Jon Gordon
Just come to jongordon.com or social media at @JonGordon11 on Instagram. I am on Facebook, LinkedIn, and I do respond if people comment to me. There, I do respond so I like to connect to people. Stay connected with someone says something bad. It's okay. You say something good, that's great too. You can make a difference, so just reach out if I can help you in any way; we'd love to. We always have a lot of events and trainings that we do. We're here to support people with their growth. Excellent, well, thank you again. Thanks for having me.
`;
