/**
 * Episode 2 — Ken Crenshaw (The Long Game)
 *
 * Source: Plaud auto-transcript, lightly sanitized:
 * - Speaker labels normalized (Speaker 1 → Seth Pepper, Speaker 2 → Ken Crenshaw)
 * - Show name correction (Unleash → Unlimit in opening)
 * - Player name spellings normalized (Maddux, Goldschmidt, Deion Sanders)
 * - Email address reconstructed from ASR fragments
 * - Reformatted to [HH:MM:SS] Name blocks with paragraph breaks
 *
 * Original ASR voice/fillers preserved deliberately.
 */
export default `[00:00:02] Seth Pepper
Welcome to Unlimit Your Potential. I am your host, Seth Pepper, and have a really rare treat to be able to talk with someone that I would consider a peer, possible mentor as well, Ken Crenshaw. Thank you for coming. This is going to be a lot of fun.

[00:00:20] Ken Crenshaw
Thanks for having me. I am excited.

[00:00:22] Seth Pepper
This is going to be good. We've had many conversations, and I know that you have this history with baseball. It started with basketball, personal as a player. You were telling me a little bit about your father, so kind of being around greatness possibly. I thought that would be kind of a cool place to start.

[00:00:45] Ken Crenshaw
I grew up in a tiny little town in New Mexico called Carrizozo, less than a thousand people graduated with twenty three people in my class and I had a superhero dad. He played for the Philadelphia Eagles and he played in our small town, went on to New Mexico State, and that was I think probably my origination of what greatness looked like. I am like wow, I got a pretty great dad and obviously an incredible mom too that just loved to serve people. And I think that's one thing I learned from her. My dad went on and played at New Mexico State and eventually the Eagles.

[00:01:25] Ken Crenshaw
It was almost standard that you played sports in the town where you grew up. We only had football, basketball, and track. We played Little League baseball, but that was the only baseball experience I had. I was naturally a pretty good athlete, and I went on to New Mexico State where I had a football scholarship. But I really didn't want to play football, so I thought, "you know what? I'm going to walk on in basketball." So I did that and that Christmas break went home for a couple of days and ended up tearing my ACL. And tried to play with it back then. They didn't have MRIs and all that stuff, so we didn't really know exactly what was wrong, but I knew it was hurt just not how bad. And so I rehabbed it for about a year, and that's how I got into the sports medicine athletic training side was doing that. And so didn't know anything about baseball, but the next year I hurt the knee again and then had to have surgery. And then I thought, wow, I just love what these people are doing how they're servicing.

[00:02:25] Ken Crenshaw
Athletes and helping them get back on the field. And so fast forward, four years later I was working with the baseball team. I'd worked with all the different teams at New Mexico State and I was working on the baseball team and I thought, Wow, this is kind of cool. And I had a friend that was with the Pittsburgh Pirates. And he said, we're going to have a summer job if you want to do that. And I said sure. I'd never been out of the state of New Mexico. So I just said, "I am all in." And I jumped into probably an uncomfortable place in my mind, which was sign on with the Pirates and I went down to Bradenton, Florida, and spent about a month there. And then they shipped me off to Princeton, West Virginia, which is one of the minor league teams that we had then. And then did that for the summer, which was an unbelievable experience. And I was doing everything that I wasn't trained to do, which was take care of athletes.

[00:03:22] Ken Crenshaw
Promote some of the strength and conditioning I actually knew, but coordinating the buses and the hotels and all these other things, I didn't know anything about. But it really helped me learn life, and I think that really perpetuated me forward in my baseball career. One of the things that really changed my life was a coach in high school, Coach Ron Becker, when I was a freshman in high school playing basketball. He just happened to stumble into our small town. And he was an incredible player himself. He played at the University of New Mexico, was like a first team academic all-American. Grew up in New Mexico himself, probably about an hour actually from where I grew up. And he went on to be one of the all-time greats at the University of New Mexico, and then started coaching, but kind of had this coached at the University of New Mexico, and then went out to some high schools and junior college and all these things.

[00:04:19] Ken Crenshaw
And how he landed in our town, I don't even know, but man, one of the greatest gifts I ever got. And he changed my life. And I say that because I still remember it like it was yesterday. I was a freshman in high school, Very talented and at least that's what he told me and I think looking back, it probably was. But I remember it was right before Christmas, we had a basketball tournament. And I was good enough to play on the varsity, But he recommended that I not be on the varsity to the actual head coach at the time, which was a track coach. And, he saw the talent and the greatness in me that I couldn't see in myself. And he recommended me not to make the varsity team, but he put my best friend who was another freshman on the team. And so, the next practice I came out and I can't imagine how I looked, but it couldn't have been good.

[00:05:17] Ken Crenshaw
And you know, I was probably moping around and being a punk freshman. And he came up to me after practice and he said, "Hey, you know why you didn't make the varsity team?" And I was just miffed like, "Yeah, whatever coach. What do you got?" And he said, " I told the head coach not to put you on the team because you're the most talented kid out here. And until you learn how to go all out, you'll never be as good as you should be." And I was so pissed at the time. And then he said, "Oh, and secondly, he goes, 'You showed up to practice just like I thought you would.' Moping around. He said, 'You know you'll just never reach your potential until you learn change.'" And he just walked off; he left me there. Man, I was so pissed; I was just like, "I am going to prove this guy wrong." And I had that mentality. And then what he did after that changed my life. First, he challenged me; he saw the greatness in me; he challenged me.

[00:06:16] Ken Crenshaw
And then after that, he just kept serving me. After I would go out the next day in practice and go all out, he goes, " T hat ' s what it's going to take for you to be, as you know, reach your full potential." And man, that just he just fueled me after that. So that carried me through high school. And, we had some incredible moments where he just kept serving me and showing me how good I could be. And man, that just. But I subsequently went and coached with him after that but, It was so powerful, it just changed my life. Which in effect changed so many other people's life through what I do now. And it's all because of him.

[00:06:54] Seth Pepper
So when he noticed greatness, this is part of our formula that we're bringing to the surface: greatness. What is greatness? It's a tangible thing, maybe intangible tangible, almost like a radio frequency that you can see in someone or feel in someone. How does that affect how you work now? Is that still part of it?

[00:07:21] Ken Crenshaw
Every day? Every day because I think inherently people can't see their own blind spots;, they can't see their own greatness because of their own limitation in their thinking. Really, You are kind of the sum of all your thoughts is the way I think about it. So most people have layered on, Some sort of event when they're younger, that gives them the thought that they're not good enough or they're not whatever they are, not enough of something. And I call it "not enoughness." And you know how that actually drives some people is incredibly powerful, and then how it limits some people is incredibly detrimental. Is the way I see things now as I've gotten older and created like my own understanding and my own awareness, which I think is.

[00:08:09] Ken Crenshaw
Is one of the biggest things to somebody being great creating, understanding of yourself what really drives you. And I know that's why me and you connect so well because of the efforts, which always was really powerful thought in my mind when I was talking to you. Wow, how did he click that? And I think that is probably something that when I look at, I see the greatness in people that they don't see. And then I always say, "I am going to just challenge them to see it themselves and then start helping them discover how most of it's just in their thinking." Obviously there is a physical limitation to being at the very elite level. Which I've been lucky to work out for thirty eight years. Some of the greatest players that I've ever played, worked with a lot of Hall of Fame players, and it still really comes down to the mindset.

[00:09:08] Ken Crenshaw
And the way they're thinking, and some of those greats, they use what they consider not enoughness to drive them. I am going to prove you wrong. Which was my moment: I am going to prove this guy wrong. And then there is others that I think just think beyond, like they don't get caught up in their "I am not good enough," but they get caught up in competition: like how do I beat that other person? And those that can really get with themselves and be aware of what they do well and not do well, I think that's one of the components that helps them be great.

[00:09:47] Seth Pepper
That's part of my excitement to unwrap and unravel some of your history. You've been a part of the great organizations, I think, right? Well, we like to take and interweave your bio into the story arc of our conversation. If you don't mind taking us through some of the experiences you've had, from basketball to baseball. So kind of an outsider, but now you're inside. What are some of the journeys you've been on, you know, at the highest level baseball is World Series? So you've been involved with a number of World Series experiences. Take us on a journey.

[00:10:33] Ken Crenshaw
I started with the Pirates. I worked with them three years in the summer, and they were in the minor leagues. You get to be with some really elite players that went on to be really good major league players. And then I got a job as the strength and conditioning coordinator with the Atlanta Braves in the early nineties, actually ninety one through ninety five, which were some incredible years. Ninety one we lost to the Twins in the World Series. Ninety two we lost to the Blue Jays in the World Series. Ninety three, we lost to the Phillies in the National League Championship. Ninety four was actually a strike, and ninety five we ended up beating the Cleveland Indians in the World Series. So my time with the Braves was incredible. I had some incredible players, a lot of Hall of Fame players. Maddux, Smoltz, you know, pop to most people's mind. And so I got to be around those guys and just see what they were made of. And the way they thought, man, they just challenged each other.

[00:11:33] Ken Crenshaw
So well, they almost didn't need a coach because they coached each other, which was really powerful. And when I saw that, I started to see what greatness really looked like. Deion Sanders was actually part of the team too. So when you start looking at all the players, I've been really lucky to cross paths. Hank Aaron was part of the organization. Willie Stargell was part of the Pirates and the Braves to a degree when I was there. So I got to talk with a lot of the greatest players that ever lived, and I was just like, "Wow, okay, this is kind of cool." And I didn't know the goal that I was getting into. And then subsequently, I moved on to the Tampa Bay Rays. They were an expansion team and started there in nineteen ninety six. We again had some elite players: Wade Boggs, Fred McGriff, all Hall of Fame players, just some incredible players that I've been able to be with.

[00:12:31] Ken Crenshaw
Watch their routine, talk with, and then I've been with the Diamondbacks for twenty two years. And again, you know Randy Johnson's and you know Paul Goldschmidt's and Luis Gonzalez's, and just so many great players. One of the things I always tell people, I don't have many claims to fame. But I have one: I've actually worked with the last three pitchers that have won three hundred games in the major leagues. Which were Glavine, Maddux and Randy Johnson. And it'll never be done again. Three hundred games is like this unreachable spot in today's world. But yeah, I've been really lucky to just be a part, not necessarily the guiding force in all of them's career, but like be a part of them.

[00:13:16] Seth Pepper
And what's interesting, we share this connection of being curious and being learners. We're coming at it from two different directions, maybe physical and then mental, but we speak the same language. So how does that sort of coincide the mind and the body connection? If you could take because you also work with kids as well. What are some of the things that you've learned along the way that help?

[00:13:56] Seth Pepper
Helps people, like working with a major league pitcher. And he actually, when he relaxes, he can throw faster. He says, "When I try to throw, like really force the pitch, like really try it slows the pitch down." So that could be a metaphor as well.

[00:14:17] Ken Crenshaw
I am spot on with the way you think about things too. We've talked about it a lot. I think resistance is probably a key word. Resistance is good in a sense that it creates more strength if it's resistance training or if it's mental resistance, so it actually builds some resilience until it doesn't. And then when there is this kind of switch, that's why I identify with you and the effort switch. If I am physically good enough and strong enough, which I've seen a lot of players at the major leagues that are.

[00:14:55] Ken Crenshaw
Physically super gifted, but they can't stay in the major league. They're not good enough because of their mental resistance, which becomes a problem. I think you know stress is good until it's not. And I think what I've seen is that if there is too much mental resistance, then it creates physical inefficiency. How do they actually start to understand that it's my thinking that's creating resistance in my body? A loose, highly reactive body is going to be way more efficient than one that's tense and anxious. Then it can become very reactive, which baseball is certainly a reactive sport. I just see that once they can get some freedom and ease within their own mental space, then their physical qualities start to jump up.

[00:15:50] Ken Crenshaw
A lot of players don't understand because some of them understand work, work. But they don't understand that if I can actually just get some recovery or freedom in my mental space, then all of a sudden my whole game changes. And I've seen that over and over. So I spend a lot of time even in that space with players or even if they're rehabbing, I'll generally have more time with them, so they don't have anywhere to go or to play. So guess what? We get to hang out a lot and then I can generally start to show them how their own thinking is actually limiting their physical capability. And then, when it comes to kids, I love working with kids; they're just so adaptable, so impressionable. And I've got a lot of kids that I work with from multiple different areas. Coach a lot of kids one on one with hitting lessons, and then also coach a girls' basketball team. What I've seen in kids is that they're very curious generally.

[00:16:48] Ken Crenshaw
They want to be good so that they can get recognition. They're kind of at the stage in their life where they don't really know what they want, but they all love to be recognized. And I think humans in general want to be important and recognized and belong to the tribe. And what I've seen is most effective in that space is really getting them to see again, kind of what Coach Becker did to me: that you have greatness in you, and you have probably a purpose in you, you just don't know what it is yet. And so helping them discover what it is that they really love to do, and then showing them how they're playing the game. I think about the way most people play, the game is like you are either playing to not lose, you are playing maybe to win. There is that middle category, and then there is the third category, which is playing for the love of the game. And I think that's what I saw with some of the greatest players I've ever worked with. They just played because they loved the game. So now that gives them freedom in their mind space.

[00:17:46] Ken Crenshaw
And I think the other thing that I've really seen a lot of success in the last few years is decoupling the relationship between parent and kid. Because generally, the kids are trying to please their parents. They're trying to fit into a group of other kids they're playing with. The parents are judging themselves based upon their kids' results, and so there's this resistance between the two, even though they're both trying to do the same thing, which is get this, I would almost say, mental reward. And so when I set them down together and I just say, "Hey, you know, father daughter, look. You love your daughter, right?" And they generally like, yeah. I said if you didn't, you wouldn't be bringing her over here to work with me. And oh by the way, you know, your dad loves you, right? And they generally say, yeah, he does. He's bringing me over here and then I'll generally ask.

[00:18:45] Ken Crenshaw
The daughter or the son say, "Do you feel like you're trying to please your parents?" And it's generally yes. I want to please them because they're bringing me over to lessons. And then I ask, or I don't know if I ask the parents, but I generally enlighten them on. Do you know that you're probably judging yourself based upon your kids' results? And they generally start nodding their head yes. And then I said, "Do you see how these two things are actually not symbiotic? They're actually detrimental to each other." And so, when they start to really get that click of "oh my gosh, I am actually limiting my daughter," and the daughter starts to go, "yeah, I am trying to please my dad. Why don't I just please me and enjoy and love the game?" And so, when I can really get them to both see that, the whole game changes for them physically. I see a different player. And that to me is what makes it powerful. And that to me has been one of the most powerful tools we have in our lives.

[00:19:44] Ken Crenshaw
Totally different.

[00:19:46] Seth Pepper
It reminds me of one of the recent sessions I work with one of the top NHL players, and he's very aware. Especially after we start working together, he's able to share these conversations because you don't really have these conversations that often. He said, "When I look back, I think the kids that love the sport the most generally end up becoming the best at it." Where would you take that? As far as love and the connection to the sport.

[00:20:17] Ken Crenshaw
I think when you say they love the sport the most, I think those are the ones that enjoy it the most. Because I've had players that are ultra-driven on things. I think they felt like they were slighted when they were younger—like 'oh, you're not good enough to play,' or got made fun of in school. It channeled all of that mental angst to prove people wrong, so part of that is awesome. But later on in life, you saw that it actually wasn't rewarding to them; they're still kind of miserable. They achieved some amazing things and they're still miserable. So it's like, well, I don't know if that's worth it? Or, what if somewhere along the line, you created the awareness that you know, if you had that same energy and passion when you were working or playing?

[00:21:12] Ken Crenshaw
That made you great. And then you could step outside of that mask or that suit after and create some freedom and joy that you really love the game. Or sometimes they have to create it during the game, to give them the freedom and ease. So it's a very complex situation. And I, just it's one of the things I try to do with kids, too. That I didn't mention is who are you without this game? Like who are you without baseball? And they've never thought of that because that's how they identify themselves. And your identity is so tied to your feelings and your emotions, in my opinion, that if you could just step outside of that for a minute and go, "Who would I be if I didn't have this game?" And then they start to see the world differently. And you know, I tell them, "You are going to play baseball for a while. Hopefully it's for a long while. But some of you may have another year or two." And then this is what I love to teach, because it's what Coach Becker taught me was life. Like, "What does life look like for you?"

[00:22:11] Ken Crenshaw
Girls' high school team, and it was pretty amazing roller coaster ride of a year. But the very last game, we played our best. And I told the girls, "I said, girls, this has nothing to do with basketball this year." And they were kind of looking like what We just played pretty good, and they didn't have a program last year. Now they got one. And I said, "No, this is about life. If you take what you learned in these last two or three months into life, your whole life will be different." And it's really about mindset and opening up your own awareness to wow, I use sport to help me in life and become a productive citizen is the way I always think about it.

[00:22:49] Seth Pepper
That's amazing. It's so true. I like to say that the journey we're on in life, we need a vehicle. And the vehicle you choose, we all go to this car lot, so to speak, and you're choosing basketball or you're choosing hockey or you're choosing golf or whatever it might be. But that's where you are going to learn the life lessons, and especially with competition, it's a great pressure test. How do you handle pressure? How do you handle failure? What's been your experience with that? Whether it's working with the kids all the way up to the highest level of the greats in your sport. What would you say the relationship to those are big subjects: pressure and failure.

[00:23:32] Ken Crenshaw
I think man I always had a profound moment when I was younger, what is pressure? I almost asked myself, what is it? It's like, well pressure to me is like I'm down to my last meal here. I always felt like, wow, we're really gifted in our country to have all of the things that we do. And so I probably shifted it to gratitude and being thankful for what I did have. And just looked at while pressure would be if I was in a country that didn't have all the things, and I'm just trying to survive.

[00:24:05] Ken Crenshaw
I think that would be pressure. And I subsequently got to visit a lot of different countries in my baseball experience in Dominican Republic or South Africa. And I saw it was like, wow, the people there are actually really happy and they're kicking around a cardboard soccer ball in South Africa. I am like, man, they just seem really happy. And we have all of these things and we consider it like we're under pressure to perform. I love to try to take people back to what is pressure. Like it's just a thought that you have in your mind. It's actually not even true. Like if I had to cut you open, could I find pressure in there? Maybe some gas, but definitely not pressure. So, yeah, I think the key thing here is that the term 'pressure' is used as a function word at the end of a sentence. But the rest is okay.

[00:25:01] Ken Crenshaw
Wow, you just really love to play the game, right? Let's just enjoy the game. And that's hard because they start identifying themselves and with oh, am I successful or am I not successful? And I think that's just such a dangerous slope. But what I've seen from the greatest ones is they really thrive on competition. If I boil down all the hall of famers that I've had, they just want to compete. They just want to test what they have against somebody else. And I think that's really what sport is all about. It teaches you competition, how to compete. Because I always tell kids, the girls the other night, I go, 'You know, it's like...'

[00:25:55] Ken Crenshaw
The thing about sports is there is a next play right after this. There is another one, or after that one, there is another one. And a lot of times, I think in life you don't have that next play right away, so you might have to wait a month or however long. And that's why I just love athletics. The next play mentality changes the way people compete, and it allows them to almost call it, get Alzheimer's and forget what just happened, get out of the rearview mirror and let me just get present at what's next. What's next, but what's next has to be achieved in the present, in the now. And that's what like I think kids when I watch them. They're either in the rearview mirror or they're way out in front of themselves. So you know, way out in front is going to create some anxiety and the rearview mirror generally will drag along some negative things. So it's like how do we create a future in the present moment? Because I think creating in your mind, what it is that I want gives you the roadmap of how.

[00:26:55] Ken Crenshaw
How can you get there?

[00:26:56] Seth Pepper
How about some quick tips on navigating the digital space? Because we both worked with high-level, high-profile athletes. I was an athlete; I was one of the first professional swimmers. I was sponsored by Nike. I had an agent. The only way you could get a hold of me was go to practice or go talk to my agent. It wasn't going to happen, so I didn't have any contact with the outside world. I was in my own little bubble. Nowadays, whether it's a kid starting out in little league and the parents managing their accounts and trying to build it up to get exposure for the D one colleges. Not that there is anything wrong with that because I understand that's the environment. Now all the way up to the highest level of high profile where they might post something might be said.

[00:27:52] Seth Pepper
And they have, if they start to get into that sort of dialogue, it's a complex world that we live in now. What would be some quick guiding rules or suggestions?

[00:28:05] Ken Crenshaw
I mean personally, I feel like the news and social media is a form of judgment. It allows people to have really strong opinions about something that they may not know anything about. If you are on the other side of it and the one being judged, it's easy to create a lot of belief and something that people don't even know about you. My form of doing is I don't really have social media stuff like that. Not that people are judging me a lot like an athlete would or kids are seeing. They're in the mentality now of likes: Am I being liked? Did I get a lot of likes?

[00:28:51] Ken Crenshaw
And I think that ultimately is, am I fitting in to the tribe? It's just a primal position that we all have built into us. I need to be, I need to belong to the tribe or it's a survival mechanism. If I get kicked out of the tribe, I might not be able to survive. I think it's really I have a distinction that I teach in The ultimate team building experience that I run, and it's called a problem or an opportunity. So what we may view as a problem, I think we do maybe people that are a little older that didn't grow up with social media. We think is a problem, and then I always switch it around: Is that a problem? Or is it actually an opportunity? And I think it's an opportunity for younger kids to get more reps at stepping away and go, 'That's just somebody else's opinion. What do I believe about myself?' And I know that albeit easy to say, hard to do.

[00:29:49] Ken Crenshaw
I like to talk to kids and players. And I said, "It doesn't matter until you read it." So if you just don't read it, it doesn't matter. And because players get hung up on that a lot. You'll be in the clubhouse and somebody will go, "Hey, did you see what so and so wrote about my other teammate?" I am like no. They're always kind of look at me like man, you don't know anything. And I am like yeah because I don't want to. I just gonna be present with you right in front of me. I think the greatest teams are connected, and they see that belonging with each other is what makes the team great, and that's one of the things that I love. I have my own course in teaching it, but it's like how do we build the ultimate team? How do we build the ultimate belonging? And I think that's where you step away from all of the judgments in the social media world. And we're just with each other. Everybody put your phones away and let's just be with each other. And I think that is the coolest thing about a team.

[00:30:48] Ken Crenshaw
And when you are with the best teams I've been on, the ones that are like World Series teams, they just have a way of really enjoying each other and having fun with each other. The ones where each individual is stuck up on their own results or their own successes, those teams generally don't play the best.

[00:31:11] Seth Pepper
So I am going to switch just a little bit because you brought up something earlier. You brought up a few. A lot of golden nuggets here. When I started realizing that the joy is one of the greatest performance enhancers, ten-year-old self, Ten-year - old joy of going back to being a little kid and just feeling it through all your senses, being present, being curious. When I started working with Major League Baseball, the Dominican Republic became this interesting.

[00:31:46] Seth Pepper
Why is there a coach specifically on every single team? It seems like there's a Dominican Republic coach. It's a small, relatively small country. Now I know that their focus is on baseball; the culture is around baseball. But what I found interesting is the joy. They have a level of joy, whether it's a college player because they're playing at all different levels, all the way up to Hall of Fame players—and it's been described to me that they're still playing like they're playing as a kid, even when they're playing in the World Series. Could you speak to that? Could you have personal experience with that?

[00:32:24] Ken Crenshaw
I think I see that for sure, having been there several times and seen a lot of the younger kids that come up. Anytime after sixteen is when they're actually eligible to be on a major league team, which is far younger than what the American kids do. You can drop a kid out of high school. I think they show up that way for sure. It's like, man, where they came from, they don't have anything. So wow, this is an opportunity for me, not only to play what I love to play, but be able to support my family. So there is a whole other level of what they consider pressure on supporting their families too. They start out with a lot of joy and freedom and playing the game. And I think it allows their natural.

[00:33:12] Ken Crenshaw
Physical capabilities to come out, and then there's a point where they start feeling "quote pressure" too. And you know, to become even support more people, so I do see that. And then I also see, as they start to go up the ladder, there is some pressure that inherently makes them not their best. And then there's other guys that just can stay in that space of freedom and joy, which is something that I never understood. But you are the one that probably opened my eyes the most. When you were talking about one of the players you worked with. And hey, what did it feel like when you were ten years old and you were skating down the ice? Because I think we're kind of all linking together or what really drive us when you really look underneath the hood. You are like wow, that's amazing. You know, I think the feeling of just the air blowing through my hair and just.

[00:34:10] Ken Crenshaw
Whatever it was. That's something to me. I love to try to take the Latin players are very visually oriented. They learn really quick if they can see something or see another player that they can mimic. They're really good at it, whereas American players learn a little different because they're used to sitting in school and having to pay attention and all that. And a lot of times in Latin countries, they haven't had as much schooling where they had this set in there. But man, they are so good at visually learning, but it's showing them what freedom and ease looks like, and then they can actually mimic it. And I think that's something like I said when I learned from you is how do I take them back to that ten year old self? And even American players, I'll generally ask them, "Hey, what's the or high school kids that I work with? Hey, what's the funnest game you ever played in?" And they'll be like, "Oh," you know two years ago.

[00:35:06] Ken Crenshaw
They know right away, and I always ask, 'What color jersey were you wearing?' They'll know that too. And then say, 'Well, what made it so fun?' And you know they'll tell you whatever it is. I hit two doubles. Generally around success. Every once in a while. It's just with my teammates that was awesome, which is a really powerful moment. But most of the time, it's tied to I had a really good game. But I am like, yeah. And how did that feel? And when they can get that emotion and feeling, then I think there is something really powerful. Paul Goldschmidt. Dear friend of mine and I love the guy to death. He's just he's one of the he's going to be a hall of famer, but he's one of the best I ever saw with the mental game. And he used to sit in the dugout and he would be looking down the dugout, but he would look like right through everybody. And at first I was like, is he looking at me? And you know I couldn't figure it out. And so finally one day after the game's over, you know I would ask him well what were you doing in that moment? What are you doing that? He goes oh I just visualized a ball that I hit.

[00:36:06] Ken Crenshaw
Double A, and I am like, "Okay, well, that was three years ago." And I go, "Where was it?" He said, "I was to right center. Was it a homer?" And he's like, "No. It was actually a double off the wall." And he goes, "Why do you visualize that?" He said because it takes him into the space that he wants to feel the swing feel that he wants. And I am like wow, that was really cool. And then so I started trying to deconstruct everything you did, and I said, "Oh. So what happens? Then?" He goes, "Well, then I step into the on deck circle and then." From there, I just watched the pitcher and try to get the timing, and I don't think about anything. So he had this process for how he got to actually step up to the plate and be ready. But he had mentally rehearsed all of these things that gave him this freedom and peace to be who he is. And he was so powerful at that and very disciplined to it. He would do that all of the time. And even when he wasn't going good, he always said something to me.

[00:37:05] Ken Crenshaw
It said, "It made a lot of sense to me." He's like, "You know, when I am really struggling in my swing, I just realize that t here is a lot of other places in the game that I can help the team." I am like, "Whoa! Nobody says that. Like they're generally trying to help themselves." And he's like well i can If I can get a runner over, or I can play better defense, or I can base do base running really well. That's how I help the team. " And, i clicked in the moment That's how he depresurizes, if that's the word you want to use. Is how do I help the team? And I think when we look at most athletes or most people in general, we think how do we help ourself first. And it's one of the greatest lessons I ever learned in life. And I think probably learned it from my mom. My mom was a she worked at the welfare department, her whole life and served people. And she just you know when I saw if you serve others, it actually gives you peace and freedom to be the best you can be.

[00:38:01] Ken Crenshaw
The double down is you actually get the reward back of feeling this sense of purpose and this sense of belonging because you served somebody else. And I think that's a really powerful lesson that if most athletes could get, or just people in general, is how do I love and serve somebody else which actually serves me. It's really powerful. One of the things I've seen in at least Paul Goldschmidt is he's just so amazing and so simple. Simple in his approach, but those are some things that I learned from him.

[00:38:34] Seth Pepper
You mentioned, I'll put it into my words of 'team first' versus just because in my own coaching, we talk a lot about your optimal performance. And so I use a simple formula: your optimal performance equals your ability minus resistance. We're working on resistance usually because that's self-inflicted. And so, to reduce the resistance, now you mentioned earlier the effort switch, so of course we have to get to that. To reduce the resistance or actually remove it, we've gone through this discussion with some of the players of thinking team first versus data first or stat first.

[00:39:26] Seth Pepper
Because that's thinking just of the individual. Once you start to get outside yourself, it's not just about me. The efforts which connect to your experience with your coach, seeing your greatness. And then my experience of getting second and my coach saying to me, "Why are you apologizing for your greatness?" Next time, because it happened twice, he said, "Why don't you just go take it?" And then the final chance that I had last year was standing behind the start, and all of a sudden, this moment just kind of clicked. There was a switch that went off. I didn't even know there was a switch that I could click. That was the "eff it" switch: "eff this," I am just going to eff and take it. And it was a moment; it might sound aggressive, but it was actually like a moment that I might even say religious or spiritual where it was like this transcendent thing we see in Star Wars when they talk about it. It's based, Star Wars is based on mythology.

[00:40:25] Seth Pepper
Joseph Campbell, so the life force, trust the force. So that to me fascinates me because all of a sudden I went into a level I didn't even know was possible. It was like I was in a race car, and all of a sudden I found the turbo button. What would you say as far as because I think that starts to get into team first? It might be something that's non denominational, but I actually like to talk a little bit about faith, spirituality, those sort of things where what is it when we can just get lost in the moment and we're at our best?

[00:41:02] Ken Crenshaw
It's a great question. I am a very spiritually oriented person. And I think when you can really sift down to the emotions and feelings and beliefs, which are all intertwined together, it's a very energetic piece. When I look at a spectrum, I have fear on one end and love on the other end. But love and faith are the same thing for me. There is a different vibration in this fear space, one of probably resistance. If you look at the way waves work, then you start to feel or energy works, you start to feel wow that's the vibration that's.

[00:41:50] Ken Crenshaw
Going to create more resistance in my mind and in my body. So I am not going to be able to function at my best when I have more resistance. So again, it goes kind of back to what we were talking about: like, well, you can play with a lot of fear, or you know, or you can play with a lot of faith or love. And then there is somewhere in between all of that, that people will fall into. They'll be like, 'Wow,' against this picture, I really got a lot of faith because I've already smashed this guy, two or three times. But against this guy, so you are playing in this continuously undulating mind space that I think if you can really get to and just get to faith. And I think that's why you know a lot of athletes that I know that have achieved some high chains. They have a lot of faith or they, you know, if it's a spiritual faith or whatever, they just believe that they can do it. And cause I've seen guys that aren't talented at all, they just believe in themselves and they'll just.

[00:42:49] Ken Crenshaw
Tell you that they believe in themselves, and those guys have been some of the greatest players. They're not the most physically talented by far. And then there are ones that are super physically talented that don't believe in themselves. And I think it's really like belief in yourself is really the difference maker, but that takes awareness. To believe in yourself, which kind of the experience you felt is like there was a moment you said, "You know what? I actually am what he told me I was." But I haven't believed it till now. And I think, you know, the gift that I was given, on this earth. And God gave me this gift was to see the greatness in somebody else. And then I always say, "Somebody's waiting for you; they're waiting for you to see that greatness in them." And when is it that's going to happen? Like when are you going to show up for them? Because we all want to show up for us, and I think to me that's like a limited space of.

[00:43:46] Ken Crenshaw
Fulfillment or freedom for yourself, because if I show up for myself all the time, you are going to be that person we talked about earlier. You have all the money you want, you have all the fame and success you want, but you are still not happy. And I think that's where I look at go. Wow, I have faith that if I just show up for others and I see the greatness in them and I start challenging them and I start being that for them, then the whole world changes, or at least for me, because I feel like that's what I call purpose. That's what my purpose is. And I probably didn't discover that until I was about forty five years old. And I don't even really know exactly how, but Coach Becker gave it to me when I was fifteen. Probably gave it to me again when I was twenty one, and I started coaching with him. He started talking about, "Hey Ken, you know what our job is? It's to take two of these kids and make them better than they ever thought they could be."

[00:44:43] Ken Crenshaw
Is what he used to say, and I was like, kind of scratching my head, like Coach only two of them? There is fifteen here. I'd never said that, but I was thinking that. And then what I realized is like, if we changed one of them's belief in themselves, and we showed them how to achieve the things that they want, and even above what they believed, which is one of my purposes, I am that I help others achieve more than they believe they could through my words, my actions, and my serving them. And when I saw that if we change one of them, it's like this herd mentality. Guess what? Then the next one's going to be like, "I want to get me some of that." And then it's our job as coaches or mentors, or just I think people in general is like, "How do we love and serve people to see the greatness in themselves?" And then that just perpetuates throughout the team. And I saw when I would go back and coach with him at my high school, man, he changed the whole world there. He changed so many lives.

[00:45:40] Ken Crenshaw
And so, that has always been my quest. Or as I got older, it's like, 'How do I do that with my teams?' or 'How do I step into my organization and not? It's not a doing; it's more of being. Like, who do I have to be? Who do I have to show up every day as to make an impact on other people's lives?' Not for me; none of it's for me. It sounds really weird because it is very unique. And people ask me that all the time. Like, no, I am just love and service for you. And they're like, 'Wait, what's the catch?' There is no catch. Like, that's a I think a lot of people don't understand it because it's pretty rare. But that's what I've understood throughout my life with all of the interactions and the people that I've come across. And the successes and failures that I've stepped into are really that awareness that's allowed me to step into that space.

[00:46:35] Seth Pepper
Something interesting when you are around Ken. Ken will come back after a few conversations, maybe even the first conversation. He said it a number of times throughout words. He'll come back to you and he'll say, "You use this word a lot." And I've said this in my own work: Your thoughts become your words, become your actions, and they're all connected. So when you start to think clear, you start to get more focused. Then it's going to bubble up in your words, your communication, whether it's written or it's spoken. And then it changes your actions, it changes the environment and the people around you. Why do you notice words?

[00:47:17] Ken Crenshaw
I guess I've discovered over the years that we all learned everything we know through words or language. That's how we developed every thought, feeling, or emotion. We couldn't describe the emotion if somebody taught us what that actually meant, there would be no connection. But the words that we use actually create the world that we're going to live in. I'm not saying the outside world, but the inside world that we develop in our own minds and subsequently, the emotions that we feel. I think when you can really simplify down to it, it's actually the words. A word that I made up may mean something totally different.

[00:48:01] Ken Crenshaw
To me, than you, but that word creates that emotion feeling. So I've had the debate before. Is it? Is it the actual word that creates the emotion? Or is it the emotion that creates the word? But you wouldn't have the understanding if you didn't have the word first. So I think language creates our world, and then emotions are really what guides us to I want to avoid that emotion or maybe I want to feel that emotion. And that really starts to guide the way we walk through life. And I think one of the really powerful things is understanding that we have a choice in all of those. Like the words you speak to yourself, or the words that you are going to hear from somebody else, are all your choice. You get to choose whether I am going to make those mean something or not. And I think when people can really, or kids or athletes can really start seeing. Wow, that's just a thought that I have or a word that I have in my mind that.

[00:48:59] Ken Crenshaw
That I can actually change if I want. You can go anywhere you want instead of putting these self limitations on, which we all have. I always say the people I coach, we all have self limitations, and anyone who says they don't, I think they're off. It's when we can become aware of them, or we have a powerful group of people around us that can help us see them. That's when we can get there quick. One of the things I've learned is it's one of my key foundational teachings: there's more power in the team than there is in you. Once I learned that, I was like, 'Wow, your team can help you get to amazing places really quick.' And there are individuals too, but that team environment can just change so many things for you. So quick, if you're open and vulnerable and willing to step into that uncomfortable place, you can find some stuff that'll.

[00:49:55] Ken Crenshaw
Help you and the team in a really quick manner

[00:49:59] Seth Pepper
Awesome. To kind of go back to the word 'greatness,' we were discussing because when we get talking. We were talking about the difference in the greats. We talked a bit about Kobe; you mentioned some other names. When you see the behind-the-scenes of the great ones, what was it like as far as their relentlessness? Because I remember this with Roy Williams. It's an interview he was talking about because he was kind of connected or labeled as a person that discovered Michael Jordan. The first one to see him and really heavily recruit him. He talked about Michael Jordan just having this level of intensity. He just worked at it.

[00:50:55] Seth Pepper
And then he also, when he became Michael's, he was the assistant coach at the time. He challenged him on that because Michael said, "I want to be the greatest that's ever played here." And he says, "Well, you are going to have to work harder." And that's when Michael came back and he said, "I promise you no one will ever work harder." And he lived up to that. What do you do? How do you speak to that as far as if you are going to put someone on point and say, "You really want to be great at this? You really want to win?"

[00:51:25] Ken Crenshaw
This is what it's going to take. I think that really comes down to your own desire or your own attitude. Earl Nightingale used to say, "attitude is the secret sauce." It was probably before a lot of people's time that might be listening to this. But it's like, at some point, you may get challenged and then say, well, that's cool. But I am not willing to sacrifice. Or, discipline's another one. I don't have the discipline to actually step into that space, which is all a thought in your own head; it's all a mental limitation. I just think, first of all, the desire and the attitude that I am going to be relentless at, it may take time, and it may take the right person challenging, which is certainly what it did for me. Like when Coach Becker challenged me, and my dad was a high challenge guy, too.

[00:52:22] Ken Crenshaw
Like that, just stepped me into another level because I could either say, "Well, I don't want to step up to that," or I do. So that's kind of up to each individual person. But all the greats that I've ever had, they are relentless at being curious. And then the second one is creating awareness around what makes them good. And I think they know that and they know, "I do this really good" and they don't take away from what they do really good because a lot of people or athletes will get limited by looking at all the things they don't do good and focus on that versus, "I do this really well." Let me just be even better at that and then bring along those weaknesses with that kind of relentless chip away attitude that you talked about with Kobe. He was just okay doing the basic boring things more than anyone else.

[00:53:19] Ken Crenshaw
And I think you know, part of my I've coached kids in high school basketball, basketball mainly, but some hitting stuff along the way. But what I figured out is that the simple things win. Like who can do the simple things in basketball, you know, shoot, pass, catch, dribble, play defense, and you know what I consider part of defense is boxing out. And when I look at it right now, like we just got done with our season and I am like wow, if we could have just passed, catch, box out a little better, we probably end up eleven and five versus eight and eight. Like that's simple. We don't need a new offense, more effort, or we just got to do the simple things right all the time. And I think most people don't have the discipline or they're so enamored with finding something new. And I think that's where our society's at with social media and all that. It's like oh, next thing, let me find a hack, let me find a shortcut, and there are no shortcuts. It's like if you.

[00:54:18] Ken Crenshaw
Are taught. Hopefully, you are around the right people that teach you the fundamental things that really make the difference and do those all the time. And what I figured out is it's I have a saying: "It's simple hard." It's really simple to do, but it's really hard to get that. And I think again, when I look at all the greats that I've worked with, it's like they do this, these simple things relentlessly, and that allows them to get to these spaces that everybody's wondering how they got there. But I am like well they just do the simple things. Things all the time. It's like Paul Goldschmidt again. I am like, if you went and watched him in a day and you followed him around, you'd be like, "Wow, that's really simple. I think I could do that." But he does it relentlessly well every day. Excellent.

[00:55:01] Seth Pepper
So you said something earlier: doing being right? You said it really quickly, but that's a major part not just of performance but life. You obviously work with these players; you care about these players, eventually their careers are going to come to an end, that transition point. What have you been able to be there as kind of someone that could guide? Or maybe it's just being able to suggest now in reflection of how to make pivots so that we're more than the game. That's life too.

[00:55:40] Ken Crenshaw
It's a great question because I think most of these athletes think the game's never going to end. They make plenty of money, and then what you see is when they get out of the game, they don't know what to do. I've always tried to have some sort of impact on them to see, who are you going to be after this game? Who do you want to be? Because they haven't even thought about it most of the time. But I heard a saying a long time ago in my first couple of years in baseball: the stars rise to the top.

[00:56:15] Ken Crenshaw
All the people that they poop on the way up are going to poop on them on the way down. Because you're not going to stay at star level all the time. You're going to drop back down. And I think when I look at it, they haven't considered that in their life. So it's like trying to teach them younger kids, like, who do you want to be like outside of baseball? And that's why I've been doing it with kids that are 12, 13, 14 years old. And it just shifts the way they look at the world. Because I always say, We don't see the world the way it is. We see the world the way we are. If we're being shitheads, then guess what? We're going to see a lot of shitheads. It's just the way that it plays out. But if we're being really loving and serving people, we're going to see a lot of love and service out there. So it's shifting them into understanding, like who you are being will outweigh anything that you do.

[00:57:13] Ken Crenshaw
Your words and your actions start matching each other. Because most people have a lot of words, but their actions don't match that. They'll say, "I want to do A, B, C, D and do all this," but their actions don't show that. And so I am really focused on what your actions are like and who do you want to be? Because that kind of gives you the roadmap of what to do, is the way I think about it.

[00:57:37] Seth Pepper
So final section which is the pep talk. If you are going to give some advice to people, it could be specific to baseball. It could even be body management. It could be anything. It could be multiple things. What would you suggest to people?

[00:57:55] Ken Crenshaw
So I can use either salt or pepper on this. Exactly. I am going to go with the pepper. I think the final piece of advice and at least all of the great ones that I've been able to work with. And or myself is to start realizing that you are the one that controls everything by your thinking. And I think how do I create awareness? And the first thing is really having people around you that will show you that there is different ways to do it. Because one of the things I've figured out too about the great ones is that they want the truth pretty quick.

[00:58:40] Ken Crenshaw
The greatest ones want to be the best. If you are lying to them, or they don't feel that you know you are truthful or that you care about them, they're just going to go to the next person because they're really looking for the honest truth. They may not want to hear it right in the moment because they think truth helps them get to excellence quicker. Versus most people are like, 'Well, I don't really want the truth and I'll go figure it out on myself,' and they'll inch forward but they won't get to excellence very fast. Whereas the great ones are like, 'Hey, just be straight hard with me,' and boom, I'll get to excellence quicker. So I think it's really like sitting with yourself and seeing what you do well. Trying to create awareness. If it's just I always say that, you find the most out about yourself in silence. Most people want chatter and social media and just stimulation all the time, but that doesn't allow your deepest parts of your.

[00:59:38] Ken Crenshaw
Your subconscious mind to really start to experience, what is it that I want and how do I see myself getting there? And I think that is probably the most powerful thing that I've seen with some of the greatest ones I've ever worked with. They're really good at just sitting with themselves and going, 'now this is what I am committed to,' and then they put the action behind it. That's great.

[01:00:02] Seth Pepper
So you started to work more and more in projects that you mentioned earlier, which is team building. If you want to speak to that a little bit, and then also, maybe if you have ways that people can get a hold of you, I know you said you don't do a lot of social media, but I don't know if you want to give out any contact information. We can put it in the show notes as well.

[01:00:23] Ken Crenshaw
Several years ago, I sat down and started reflecting on all of the lessons I've learned in leadership. Team building and all of the components I think help create the ultimate team or the best team or the most elite team is how I was thinking about it. I started thinking, "I am like, God man, I got to write this down." So I did. I stepped back and started thinking, "Well, it's selection, it's development, it's feedback, and it's leadership and communication are kind of the five key areas that I talk around." What intertwines all of those is trust.

[01:01:03] Ken Crenshaw
So I started thinking, 'Well, how do we do that?' We're doing it at a really cool rate with our sports medicine performance team and developing. So many people are running other teams. And we're having a lot of success. But I never really stepped back and started thinking, 'Wow, how are we doing this?' I know I had a great team around me and everybody's doing it together. But when I put it down on paper, I started thinking, 'Wow, I got to hand this out to somebody. Give this to somebody.' One of my personal development coaches, Devin Bandison, who you know he? He just said, 'Well, when are you going to do it? Let's set a date and do it.' So I created what I call the ultimate team building experience, which you've attended. And it's just been amazing. I've had four of them now and the people that walk into the room and just to see what they get, I throw all the ideas, and then to see them walk away with something really powerful that actually changes their own team.

[01:01:56] Ken Crenshaw
And when I say 'team,' what most people don't realize is you are playing on multiple teams: your family team, your work team, your whatever it is, your church team. All these different teams you are on. When they start seeing, 'Oh my gosh, I am playing on multiple teams and I am playing a different role on each one of those teams,' and what I actually can provide for each of those teams is something different. And I think that's one of the things that's been most powerful to me. So you know, I love doing the team courses around, my actual real job which is being the best I can be for the Diamondbacks. So I like to teach that. I don't have an official advertisement, but my email is a good place to start: kcrenshaw@dbacks.com. So anyone wants to attend or get a session. We generally only have about twenty people, because I want it to be really intimate. People walk out of there with some good nuggets, and we have some Zoom calls.

[01:02:52] Ken Crenshaw
Follow-ups after that. It's one of my purposes in life to serve others and see the power of the team and all of the pieces that could help them or their teams take themselves to another level.

[01:03:07] Seth Pepper
I see the greatness in you. Thank you. Thanks for being with me today and for sharing everything with all of us. This has been amazing. Thanks for having me. It's been golden awesome.
`;
