/**
 * Episode 5 — Seth Pepper solo (The F#ck It Switch)
 *
 * Source: Plaud auto-transcript, lightly sanitized:
 * - Speaker labels normalized (Speaker 1 → Seth Pepper, Speaker 2 → Narrator
 *   for the third-person produced intro segment)
 * - ASR-truncated opening repaired ("Welcome to" added)
 * - Name correction: Rick Demott → Rick DeMont (Seth's U of A sprinting coach
 *   and former world record holder)
 * - Reformatted to [HH:MM:SS] Name blocks with paragraph breaks
 *
 * Original ASR voice/fillers preserved deliberately.
 */
export default `[00:00:01] Seth Pepper
Welcome to Unlimit Your Potential, the podcast where high performance leaders and everyday warriors come to break through limits and rise into who they're meant to be. I am your host, Seth Pepper, high performance coach, mindset strategist, and lifelong student of human potential. We don't just talk about motivation; we build mastery, sharpen discipline, and develop the mindset required to win consistently. Each episode.

[00:00:32] Seth Pepper
I'll bring you powerful conversations, proven framework, and real world strategies to help you elevate your performance, strengthen your resilience, and live with purpose. If you are ready to stop settling, start growing, and truly unlimit what's possible in your life. This is your home.

[00:00:55] Narrator
Ranked number one in the world. World championship medalist. Pan Pacific gold medalist, two-time NCAA champion, two-time US Open record holder, twenty-three time All American. Fastest split ever recorded. Seth Pepper didn't read about elite performance in a book. He earned it in the water against the fastest humans on the planet. His coaching career consists of pulling the playbook out of Olympians, champions, professional athletes.

[00:01:29] Narrator
And coaches, this week the chair turns around. No guest, no script, just Seth. His story, his why, and the mindset that takes you from where you are to where you are built to be. Unlimit your potential starts here.

[00:01:54] Seth Pepper
I want to thank everyone out there that is going to go on this journey with us. And you are part of this. The audience draws out what is necessary. This is an organic relationship that we have, and so when you follow us, it's going to be something I know there's so much noise out there. You can fill your day with all kinds of information, all kinds of stories, and for you to stay dedicated to this space and to be able to just lock in with us.

[00:02:29] Seth Pepper
Allow this sort of container that we're going to have bubble. That's a performance environment. I know that you are going to get a lot out of this. Your commitment is always the macro micro of are you committed to the shot? Are you committed to the next action? Are you committed to the moment? Your commitment is everything. And I know that you are going to get so much from this. On a regular basis it's going to blow my mind before it blows your minds. Or maybe it'll happen together. But I really believe that this is going to be a special journey. And I think this is the right time for this because there is so much noise. There are so many choices. Your phone is actually designed to distract you from doing things, and I say that in a loving sort of way.

[00:03:27] Seth Pepper
Your phone is an amazing tool. I think it's incredible. But in these sort of platforms, there can be a lot of noise, a lot of distraction. Another sort of silver bullet. We are not giving silver bullets here. This is not a get rich quick or get the solution quick. It's not even get the solution long; it's just get the thing going now. And keep moving forward together. And we're going to move together on this. I really appreciate that you are going to spend your time with us and trust us that you know, we can get something in this experience together. And this comes from a love again, the obsession Kobe said, "the greats all what they have in common is they love what they do." It's not about the trophies;

[00:04:24] Seth Pepper
The money, it's not about the fame. It's about loving what you do. The key phrase to that is he says, "We study what we love." Now think about that. All of us, every human being, we study what we love. So if you love getting better, we're going to study this thing together.

[00:04:52] Seth Pepper
Unlimit your potential is a phrase that popped into my head. I've always been open to the idea that there's something beyond, you can call it what you want: God, spirit, energy, ancestors. You name it. Subconscious mind. It popped into my head when I was about six years old. And 'unlimited your potential' is actually a misspelling, 'unlimit,' you know. So I see that every time. I was like, whoa, that's a very unique thing and that stuck with me. It's just the way I've lived my life with this level of curiosity. I didn't do well in school. Now I'm not saying that that's something I'm proud of, it's just what happened with me.

[00:05:50] Seth Pepper
In school for me was a curiosity as well. I am a learner, but I don't want to learn that. And why does regurgitating that information how is that going to help me? I was a bit rebellious in that sense. Not that there is anything wrong with that because there are certain professions where that works well. And that is necessary. But I was curious how I could speed up my learning, my ability to perform as a human being in the human condition?

[00:06:21] Seth Pepper
That's what I was trying. I'd get into these books because my dad was always into self-help. I grew up with all these books about speed, reading and photographic memory and training the mind. Just stuff that you just didn't hear about. And then I'd see people that could be so creative and inventive and could do daring things. My brother is a great example of that, where he just creates all the time and he doesn't really experience fear. And I would see all these differences and then we just didn't fit in. So I was always interested in if you could remove all the resistance, and you could give someone the ability to unlimit their potential, just imagine how powerful that is. Because so much of the system seems to not necessarily

[00:07:21] Seth Pepper
Focus on how we unlimit this thing. What is our real objective? Do we just want these people to be controllable and fit in? Or do we actually want to be able to harness the energy within the individual and then be able to maximize it. So that's my unlimited potential. It's a true sort of curiosity that never stops because I'm fascinated. And then it brings in the faith element because, in order for you to be unlimited, it happens like in performance tech talk would be the flow state, the zone, the moment being present. The simple of it is you are going to be in your body. Children are in the flow state all the time; they're being present all the time because they're just experiencing.

[00:08:18] Seth Pepper
Experiencing life, and they keep moving through life. They're not judging life, they're not judging themselves on winning and losing. They're just doing things, they're fully present. That's when you are unlimited when you know. The simple equation that I use is your ultimate performance equals your ability minus resistance. It's simple resistance though, it's usually self-inflicted. It's you getting in your own way. So when people ask me, what do you do? The simple way that I describe it is, I just help people get out of their own way. That's what we're doing. As human beings, we get in our own way. So I like to go back to the simple of that, to try and understand through evolution, the human body, the mind. The mind is here to keep you safe.

[00:09:16] Seth Pepper
For survival. So it's trying to assess the environment, and it's trying to go, 'Are you going to be the hunter in this moment? Or are you going to be the hunted in this moment?' And it's constantly going through these two extreme scenarios. And your mind is actually trying to guess what's going to happen next. What's interesting is that we are usually wrong, if not always wrong.

[00:09:46] Seth Pepper
But we don't have another system to be able to compare and contrast or choose, so we're making these faulty assessments all day long. And what I try to do, especially in the performance field, is to help people realize your mind is trying. Where does pressure come from? Pressure happens in situations when you care about what's going to happen. That's performance. That's if you are going to give a speech, that's if you are going to ask someone out on a date. That's if you are going to do anything important in your life. It is going to have pressure. Learn to deal with it, create a relationship with it. Where does pressure come from? Pressure is the anticipation inside your body. So your body starts to respond: 'Oh my gosh, I am going to go do this thing.'

[00:10:45] Seth Pepper
And what does your mind do? It does the only thing it can do because it can't do anything other than try and guess. And all those guesses are usually wrong. She could say yes. She could say no. I could go out there and I could win. I could lose. And it's going through these extremes. And then when you're not really aware of that, you can actually think that that's possibly going to happen. I am going to go out there on stage and fall on my face. And then you fixate on that, even though your mind was just guessing, and that becomes your reality. What I try to do is try to be curious about okay, we have this feeling of pressure. We have this mechanical nature of our mind. That's just trying to keep us safe.

[00:11:40] Seth Pepper
How do we navigate pressure so that we allow the mind to guess, but we are aware that it's guessing, that it's not the truth? I like to say feelings are not facts; they're just feelings. They feel really real because they're your feelings. So how do we move around these things? How do we use the mechanical nature so that you can actually move around the situation rather than be.

[00:12:10] Seth Pepper
Kind of like a slave to the situation, so I like to say, 'you are either writing the story or the story's writing you.' I am sure someone else has said that. Which is really, in the reality of that you are creating. Are you able to navigate pressure? To where you can be at your best under that opportunity. And it's always going to be uncomfortable. So the better you get with pressure, the more opportunity you get in life, the bigger opportunities you get in life. And that's just a very simple thing: entry-level job, everybody's doing these sort of beginner job. Managers are watching you to see how you handle pressure. If you handle pressure well and you make great decisions under pressure, you are managerial material. So it's the nature of everything it seems like in life.

[00:13:10] Seth Pepper
That the cream rises to the top. So how you handle those opportunities gives you more opportunities. For me, it's been interesting just to understand the basic nature of a human being, the human condition, and help us get out of our own way by seeing ourselves. For me, it's been a journey of just sharing and not really going to do something or be outwardly be something. Because my younger version was trying to be successful and trying to get all those trappings. And then finally letting it go, going through my own sort of internal journey. Get to the other side living life just simple life father husband.

[00:14:07] Seth Pepper
And then, once someone had discovered this past identity, the athlete, that's when it all unfolded. It seems like happenstance where someone saw my name on a record board at the university and said, 'That's interesting. Is that you?' There aren't a lot of Seth Peppers in the world, so I said, 'Yeah, that is me.'

[00:14:37] Seth Pepper
So I started, obviously telling the story and sharing it. It was a fellow parent. After they heard it, they'd say, 'Hey Dave, you heard Seth's story from another parent?' Then they all wanted to hear this story. They really encouraged me to go out and share this story. My wife, who's behind everything, realized she might have seen it even before then. She realized how we could do what they're talking about, which is go share this story. I started. I am used to being an athlete and having a coach. So I found a coach who could help me put in place a way to help people. From there, it just organically happened.

[00:15:33] Seth Pepper
The lowest hanging fruit was to help athletes because I understood that world. And so I started working with athletes, and I was also on interviews, podcasts, shows telling that story. The story really included a lot of people without me even knowing. The story involves a lot of sort of belief, faith, hard work, pain, failure. The more I would share not only the experience, but how I got through it—the tangibles of the tools—you know—I just realized that I may look at the world differently than other people. Where it's just for me—it's always like.

[00:16:32] Seth Pepper
Human condition: we're an animal on this planet. We have this body; how does it function? How can you help it to function even more? And then, performance is about that when it goes into the mental and then beyond it, understanding the faith, the belief, the trust—the something that's intangibly tangible. And once I started sharing that, I think people could relate to the simplicity of it. It's super simple because if it's not simple, it doesn't stick with me. I am just used to that because I am a person of habit of routine. I really need to do something over and over, and it has to just become part of me. I've just always been like that for a long time. I felt stupid because I didn't have a lot of complexity.

[00:17:31] Seth Pepper
Hold on to a lot of facts and knowledge, but the things that did stick stuck. I realized later that the way I looked at the world was really performance based because it was about patterns. I would look at patterns and see the difference, the contrast: was something in movement? Was something expanding? Was it contracting? Was there blockage?

[00:18:02] Seth Pepper
And just by being that simple about it, I think that curiosity would lead me to solutions first for myself and then, just being curious about others because everyone's different. In sports, it gives you a vantage point because it's egalitarian. It's about everyone having a shot, more or less. And it's metric based, so it's measured. It has a beginning, middle, and end. It has a winner and a loser. And it has stats in between statistics. And because it's measurable, it's something that everyone can relate to. So now I've shared my story with the highest caliber athletes in the world, the highest caliber teams in the world.

[00:19:02] Seth Pepper
Then started having people that would contact me from all different walks of life, and they would be in business, whether it was a CEO or a starting salesperson, or in the arts, working with film directors, working with fashion directors or fashion designers artists. And everybody whether they were ten years old or they were eighty years old could relate. And I wasn't going to be relatable; I would just share. And so that's kind of how this has all unfolded so organically, is that I say I am obsessed—the healthy version of obsessed. And obsession is love, loving what you are doing.

[00:19:59] Seth Pepper
For me, is this sort of how can we, how can I help others to be at their best more often and longer? You might call that greatness. So when I was younger, my mom was clinically depressed. I think that's where the origin story starts. I was trying to understand the difference. Why am I so motivated? And then, your mother—your loved ones—you want to help. I was always trying to help. That might be directly helping her or it might be inspiring her—just trying anything. And I think that's where the curiosity of the pattern was: differences. And I was fascinated by motivation. I was highly motivated, like I said—and then there were—as a kid.

[00:20:56] Seth Pepper
There's other kids that you go out and you ride bikes with, and you know, so we're jumping and we're climbing trees. And I was always into how do we do this better? How do we do this farther, higher? Trying to encourage myself, trying to encourage my brother, trying to encourage other kids on the block. And that's just who I've always been. And I've always been kind of a nerd. Now even though I didn't do well in school, you know the complexity of knowledge, I was always curious. I was always studying stuff. If I had fish, I would have all kinds of spreadsheets and you know, what you feed them, what are their habits, all these different things. You know their Latin name. And so, I wasn't getting any grades from those sort of things, but that's who I am by nature. And it fits what I do now.

[00:21:53] Seth Pepper
Curious, and I collect evidence. I am constantly looking around. Being in this information age, as much as it's something we talk a lot about, the kind of this, the challenges of the connectivity. There are great advantages of the connectivity. So social media we share a lot of these stories, a lot of these clips, a lot of these or like, and just all kinds of like the algorithm. And it speeds up the process. So now I have all of these clips and examples of yeah I said it. But here hear it from the source. So that's kind of my fascination: how do I surround someone or some group with evidence and give them tools and then we put in place.

[00:22:52] Seth Pepper
A loop, something we can circle back an accountability loop and it's super simple, but it works. If you show enough evidence that the great ones did the same thing, it helps to speed up the process and lock in. The podcast is a natural progression of sharing the story when I was just sharing the story in my kitchen with parents that went to working with people, and then when I was working with people, the word got out. They'd say, 'Will you go speak to groups?' So I started speaking in all types of different groups and I found myself in front of large audiences, business conventions. It could be teens. I'd stand there going, 'What am I doing? How did I get here?'

[00:23:48] Seth Pepper
I was at one where they were all business, and it was a big convention. They were going through this introduction, this promotion from, like, we have this motivational speaker and he's done this and this. The woman in the back, it's like they planted her to push the imposter syndrome button right before I was going on stage. She turns around and says, "How did you become a motivational speaker?" I was like, "I can't even answer that question." How am I going to go on the stage?

[00:24:18] Seth Pepper
I've learned to just be, at this stage, just to be myself. I took the question up on the stage and I said, 'It's funny someone just asked me how I became a motivational speaker.' And I was very honest. I said, 'I don't know if this is going to motivate you,' but I am going to tell you what my life has been like. My brother has been an important part in this. He was kind of like the first person I worked with on the sports side of things. Then I'm going to tell you the tools that I've used. I'm going to show you some before and afters. And at first, you're looking out and everyone's dressed in their suits. These are suit suits, right? But how did I get here? There was a woman that was falling asleep right away. But I started unfolding all this and telling all this, and I swear everyone in the audience became children.

[00:25:18] Seth Pepper
Because what I realized was that I was bringing the childhood dreams back into their lives. They were starting to see the unlimited mindset, the possibility of 'what if I could get out of my own way? What would that look like?' That woman woke up; she started asking all the questions.

[00:25:49] Seth Pepper
And I started to see this is really helping people. I grew up on motivation, with those tapes and the books that my dad had. I always thought wouldn't that be cool? That would really be cool to help people. But I didn't know how to get there. It's the why versus the how. I always knew my why was I like helping people. I like unpacking performance. How do we be our best as often for as long as we can? That's always been something in being able to spread the word. The podcast has just been a natural progression. I think once I started sharing these stories, and then in the stories, I do a lot of conversations and talking about talking to people behind the scenes. I like to reach out if I watch something.

[00:26:46] Seth Pepper
I'll go and see if I can get a hold of that person. I just love to connect with people and relate to people and tell stories. I would tell the stories of these conversations I was having with these top level performers, like very well known people. And I think that's the natural progression was that people kept on saying, 'Do you have your own podcast?' Because I would speak and people would say, 'Do you have a podcast? Do you have a book? Do you have a TED talk?' Those are the questions I was getting a lot, and I was like, 'No, and no.' Yes. And. So this has been a natural sort of birth that I think that now I can share these conversations in real time. And you're seeing them unfold right before your eyes. I know these people are important. I know what they've done, but I don't know exactly what we're going to talk about. And that's where the organic nature.

[00:27:45] Seth Pepper
Of my coachings is that I sit in the unknown and I sit in front of someone or I sit in front of a group, and we explore this thing and see where it goes. It happens between us; it doesn't happen just because of me. And that's what these conversations are—they're organic. And I believe that there is something beyond us that happens—that gets sort of channeled.

[00:28:14] Seth Pepper
They get lost in the moment, in the flow state, in the zone. In the moment, and I do too. That's the magic because I know that the people that are watching the podcast are drawing it out. I used to be, I've done a lot of different things in my life because I was taught to go chase your dreams, go do your thing. One time I was a radio announcer. Back when they used to decide the music, and I noticed that the music was like the community was choosing our music. What I really kind of set that the board would light up and everybody was really interested. This is not music that I would have chosen, but I had this sense of like kind of getting out of the way. It's almost like some people will talk about a book in a bookstore, just kind of drops off or sticks. It has a stickiness to it.

[00:29:12] Seth Pepper
I would do that with music selection. So back then it was records and CDs, and I just kind of didn't even know why I was doing what I was doing. And then people would just be blown away, I would be blown away, and I'd be like, 'Oh, we're all in this together.' Out of I got myself out of the way. So that's what these conversations are going to be is that I know these people are really awesome. Let's see the magic that's going to happen between us in real time. Beginning of this, I think it was always a dreamer. And then I was around, my family that were very free thinking. So my parents were kind of like out of the box. All the relatives lived on the east coast. My parents broke free and went to the west coast on their own.

[00:30:07] Seth Pepper
That took a lot. That must have taken a lot of courage just to up and leave and go start over. And then what our parents did was they were really curious too. They were really dreamers. I think I was the next generation. My parents were kind of, I might say, like they might not have the courage to go and actually do the thing, but they would give us the information, they'd give us the support, and we were kind of the next generation actually go and do the thing. And so, my mom was an author. My dad was an artist, like a craftsman, so he built classical guitars or luthiers. So I came from an artist background. No one was talking about sports; sports was not something in the household. I watched Miracle on Ice; I am old enough to have seen it on a.

[00:31:04] Seth Pepper
Tiny little television when I was young. Now we have the magical version that Disney made, which is based on the true story. When the United States beat the Russians, and the odds were way against them. The announcer even said, "Do you believe in miracles?" In the last three seconds as they beat them, and it was kind of like that question. I do. I believe so. Fast forward a couple of years later, and take this: this is one of those butterfly effects origin. All these little things add up to this big huge ripple effect. We are taking a field trip to a planetarium. Which is you go in, and you see the stars. They put these dots on the ceiling.

[00:32:01] Seth Pepper
And so, it's all about outer space astronomy. We go into the gift shop, and the gift shop has a book. And I had money in my pocket. I don't know how I had money at that age. They had this book on the Olympics; it's like a picture book, and it showed all the behind-the-scenes of Miracle on Ice. And I was like, "I have to have this." Of all things in this science museum, they had the Olympics, and so I bought it. I took it home and I just was obsessed with it. I kept going over the pictures, kept going over the pictures. And so I kind of knew, I could feel this thing building inside of me. We had moved to an area where it was cold. We lived in Idaho for a little bit, and I thought maybe the Winter Olympics.

[00:33:00] Seth Pepper
I like Eric Heiden. Eric Heiden was equal. He still to this day holds the record for he's a speed skater and got five gold medals in one Olympics. That's still the most that any Olympian in the Winter Olympics have ever done. He won every single distance in speed skating. So that's equivalent to someone in track winning the hundred yard dash and winning.

[00:33:30] Seth Pepper
It will never be done again, most likely. And Eric was a really cool guy; he was a very nice, relatable person. I was like, "Eric Heiden, I am going to be a speed skater," but I still wasn't at the age where you go out and do it—you take control of it—because my parents weren't talking about sports at all. This is going to take a monumental next leap. So then we moved back to Oregon, and that's when I saw the Olympics, the Summer Olympics. And I am watching the Summer Olympics, and I said, "Okay, this is it. I am going to see if these books my dad has on going out and achieving your dreams really work." This is going to be an experiment. So I really looked at it now; I call it a mental experiment. And I was watching the Olympics.

[00:34:27] Seth Pepper
To try and decide, I want to go there which sport am I going to do? I wasn't doing any sports. And there was a girl that won the gold medal in swimming. And I said, that's interesting. Then they started talking, the announcer who was interviewing her afterwards, said, if there is someone out there that wants to do what you just did, what would you recommend? I was kind of raised to look for timing. That seemed like a pretty good. That was a clear answer right there. Clear question, clear answer. So I said, whatever she says, that's what I am going to do. She said, "I went to a YMCA." So I looked up to see in my small town if we had a YMCA. We did. I went down there in the basement. They had two lanes. Swimming pools usually have like eight and more like this is a tiny little pool. It's more like a bathtub.

[00:35:26] Seth Pepper
I walk up to the head coach and I said, "I want to go to the Olympics." He goes, "Okay," and he kind of smiled at me because you don't hear that very often. I am fourteen at the time, so I am a freshman in high school. I am pretty tall. And then he says to me, "Well, do you know how to swim?" I said, "No, not at all." And that's when he laughed. That's when most people laugh when I share that.

[00:35:57] Seth Pepper
But it's important to share that just because that's where I started, and I had no experience whatsoever. He was a great first coach. He said, 'That's fine, but you're going to have to learn how to swim and you're going to have to learn with the kids,' the younger kids. So I started out with second graders. As I said, I was pretty tall and they came up to my waist. They kicked my butt all the time every day. But for me that seems like, for most people that might seem like a disadvantage to start so late because usually in sports, they start eight and under. And what I've learned now with what I do is it's a very unique and advantageous way to look at things because I didn't really have a past. I wasn't carrying this weight that I see so many of these professionals.

[00:36:56] Seth Pepper
Carrying from the past of old trophies, old ribbons, old achievements. I was just fully present with learning. It was this huge advantage of just hey, out of my own curiosity can I do that? Let's go try. So everything was about trying to get better. Getting better is collecting information data and whether. Performers know this, and this is all walks of life. This isn't just sports. If you really want to get good at something, you are constantly collecting information, data junkies so to speak. And if you truly want to be great, you want the honest truth always. Where are you going to find honesty? Failure is going to give you the most information. And if you can flip.

[00:37:49] Seth Pepper
Flip the switch, so to speak, on failure where you say, "The more I fail, the more I succeed." You just removed one of the biggest resistance stigmas, which is failure is bad because that's my self worth. For me that's what sped up the process of learning and growing. Ironically now with my vantage point I am able to help people. To say, if you want to have mental strength and all these sort of catchphrases, what's your relationship to pressure? How do you handle the big moments? And what's your relationship to failure? When I started out like that, my dad had shared with me this study. It was in one of his books. He always had these books.

[00:38:47] Seth Pepper
He would point them out, and he said, "just read these few pages. I think you might like that on sports because it wasn't his thing." And so it was on this study. It was in Australia. It was basketball. Three months they had three groups. First group was doing the task, second group was doing the same task, but the first one is not working. They had three groups. First group, they're shooting free throws. All they did was traditional repetition of the physical world and the physical training. The next group, there's a control group, that's the group that didn't do anything, so that they can compare. And then the third group did mental training. That's the first time I heard that you could actually train your mind. I didn't even know that. That was unique to me, exciting. What? You can train your mind? I didn't know you could do that. And then at the end, they went back and they tested them. And the first group.

[00:39:44] Seth Pepper
The traditional group improved twenty four percent. The control group didn't improve at all. And then the third group that was only trained their mind, they didn't even touch a basketball. They had improved twenty three percent. So you are telling me that someone could train their minds almost as well as their body? What's I didn't even know that. And what if I do both of those things? Then I just like boom, that was like that big "aha" moment. I am going to train my mind as much as I train my body. When you go and you talk to some of these greats and you ask them just straightforward, "What's the ratio of the importance of mental versus physical?" they usually say at the lowest they will say sixty.

[00:40:40] Seth Pepper
Forty usually sixty percent mental, forty. They usually talk about ninety five percent like the great greats because everyone in the final heat at the Olympics, unless you have a Usain Bolt. That's like a little bit of a freak. Almost everyone has a chance to at least medal, if not win the gold. It will come down to tiny little differences, and usually that tiny little difference is between your ears.

[00:41:10] Seth Pepper
And so, that became the rabbit hole that I went down, which is to understand how what is the mind? What's the effect? How can I maximize it? And so what I did was explore the subconscious mind first. Which is a good example is if you're riding a bike somewhere that you're used to. You're riding a bike to your buddy's house. You don't even need to think about riding the bike. You don't even need to think about the traffic. If you're driving, you get in the car when you want to go get some groceries, and you don't even think about driving the car. It's in the car. The car itself is a very dangerous thing if you think about it. And then also it's very chaotic because you don't know what's going to happen out there. You know the destination, the route but you don't know about lights. You don't know if they're going to be people or other cars out there. It's very dangerous and chaotic.

[00:42:09] Seth Pepper
But you are able to do this thing without even thinking about it, and then you might get a phone call on the way. So you can multitask this thing. That's the power of your subconscious mind. And when you really start to understand how much it creates your world, how much it will really steer you into the future, that's where I wanted to go. I wanted to use this sort of superpower, which I call it, or the supercomputer. So the subconscious mind is visually based, so I created clear goals. The Olympics, some other parts that would be the steps to the Olympics. And then I went and I collected some images. This is way back before, like people would talk about vision boards and things like that. But for me, it was more like a post-it note. So post-it notes, why do we use post-it notes? Because there's the bright color for a reason.

[00:43:08] Seth Pepper
You're able to stick them in places anywhere without leaving residue for a reason, so that you can visually remember to do something. They're an accountability loop. For me, it was taking a Sports Illustrated that had the Olympian that I wanted to become, cutting out that picture, putting it on the wall. Then I felt like I should have a picture of myself because I need to see myself in this. So I took a picture of myself and put it so that they were touching. And I would see that on my bedroom wall over and over. And I was constantly trying to make that future a reality. Maybe it's just out of curiosity sometimes, or it might be a conversation. This person, this Olympian is named Pablo Morales. So Pablo might, on a tough day, encourage me. On a great day, he might.

[00:44:06] Seth Pepper
Congratulating me, it was this ongoing sort of curiosity in making the future normal. And so eventually, I did end up becoming a state champion in four years from not knowing how to swim. And then eventually, this is part of what I try to work with people and groups on. Your thoughts become your words become your actions. If you go back to my origin story, I walked up to the head coach and I said, 'I want to go to the Olympics,' that's because I was clear in my mind. I didn't even care that he smiled or laughed. It didn't matter to me because I was clear up here. And I thought about it so much, I was speaking clearly, and my actions were clear because I had gone and actually done it. I was there.

[00:45:04] Seth Pepper
I started reaching out to all the different universities. I took a list from the spreadsheet I mentioned earlier. I made a list of the top twenty schools and reached out to every single one of them. I am a big person that you got to be able to talk to the person if you ever want to be in sports. You got to be able to talk to the coach if you are going to play for the coach in life that works. If you want to go do something, you've got to be able to seize that moment. You are going to actually go out there and reach out to these people. And so that's what I did proactively. I sent them a mission statement: "This is who I am." Right? "I see you. I see what you've done and what you want to do probably." And I want to go to the Olympics. So it was like inward, outward, and then it was beyond in this one.

[00:45:59] Seth Pepper
And I would send out these press packets. They had measurements, they had all of my hand size. I was like, "I am going to give them anything and everything." I am going to give them clippings. And I got a good response from all the top twenty schools. And I ended up going to the University of Arizona. And the reason why I chose that school was because I did have a choice of a few of them. The head coach, Frank Bush, he reminded me of my father. The reason why I chose Frank is because I could trust him with my ideas. I didn't care about any of the coaching. That sounds crazy because most people would look at the history. No one knew who Frank was; he was a new coach, I was his first athlete.

[00:46:56] Seth Pepper
The school at the time was going through firing an old coach and kind of had a black eye, so that the whole organization didn't look good. But I trusted him because I trusted my dad, and I trusted that all I needed was my mind, my ideas—just don't mess with my head. That was my thing. And so, my second year (sophomore year), I am going against the Olympic gold medalist, and I am beating him the whole race until the final stroke he out touches me. If you go back, that's only six years of walking up to that head coach and saying, 'I want to be an Olympian,' and now I am going against the Olympic gold medalist in beating him almost the whole race. That's the power of the mind. I always go back to the power of mind.

[00:47:55] Seth Pepper
And I got second the next year, my junior year. And then my senior year, this was your final year. And I had another coach, so you have different coaches on the staff. Frank was the head coach, and then I had Rick DeMont, who was my sprinting coach. That was my specialty, short distance. And Rick was a world record holder. He held the world record. That means that he was the fastest human being on the planet at one time. We hear world record all the time, but to actually have a world record, that means you are the fastest that's ever done this thing. He was also the first person in the sport of swimming to negative split, go faster the second half than the first half. So he was an inventor.

[00:48:55] Seth Pepper
And he was my mentor, and he saw the greatness in me before I could see it. When I got second for the first time, I was like, 'Oh wow, this is amazing.' And he would say, 'Why are you apologizing for your greatness?' I was like, 'What the heck? I don't even understand what he's saying.' He was nice; he wasn't you know. He was celebrating too but he you know. He was trying to feed me more. Like a good coach, the next time afterwards that felt like last place getting second. The second time he got me again, and that's when he could be a little more direct. And he said, 'Why didn't you just go take it?' Whoa, what is he talking about? So the last year, my last chance. I am standing behind the start.

[00:49:51] Seth Pepper
And I don't, I still to this day it was just being. It's like opportunities happen in compressed time. Do you believe in miracles? The last three seconds of that game, Michael Jordan takes the last shot with only three seconds on the shot clock. These big moments come down to little tiny moments. And so, this was what's happening to me. I was being compressed by the moment. And all of a sudden, my aunt she'd never seen me swim ever. She is from New York City. She was a nurse, and she went to this just to see the final race. She said to me afterwards, 'I knew you were going to win before it even started, just by how you stood there. You were so solid. There was a presence about you that the race was already.'

[00:50:47] Seth Pepper
It was already decided. What was going on the inside is that I am behind the start, and all of a sudden, I don't cuss a lot. It's not really my way. It's just not me. And I said, "F this race, F these people." I am effing taking this now. You fill in the blanks; it was the real word. And now I called them. The effort switch, right? But those words sound like they're maybe they could be connected to being aggressive. But this was not about aggression. This was about acceptance. This was about breaking every single rule because performance, whether a human being knows it or not, we are kind of raised in systems. So that when you go to school, you are trying to get a good grade, or you are getting a bad grade and you are not being accepted.

[00:51:46] Seth Pepper
But either way, you're going through this progression through a system and you're being measured. So you're used to looking in the outside world and asking, am I good or bad? Do I get to qualify for the next level? If you want to break a world record or if you want to be a champion, a national champ, whatever it might be, start a new business. It could be anything. You have to break rules. You have to break rules from the outside, because most people on the outside are going to say, 'You're crazy. What do you mean you want to go to the Olympics? What do you mean you want to start this new business that doesn't even exist? What do you mean you want to invent the light bulb?' Those are rules, and that is resistance. All great ones have to go through that. You have to be a maverick. You've got to be a rule breaker. The effort switch was that.

[00:52:40] Seth Pepper
I am tired of all these rules that I've allowed to dictate who I am from the outside world. But it's even more important because it's on the inside. I had all these rules on the inside, I didn't even realize. And once I allowed myself to break all the internal rules and the external rules, then I was able to really get out of my own way. That's when I believe it was like a religious experience. Because I work with all these different athletes, all these different performers, all these different people from all walks of life. I share this story like I told you, and I am always curious why they care so much? What is their great moment, their effort switch moment? And a lot of these people from different walks of life have a faith, they have a belief, they have a trust in their ability.

[00:53:39] Seth Pepper
In that moment, at least. And that's what happened, is that in order to get into the flow state, the zone, the moment. Being present, the effort switch being in your body out of your head. That's when you know as they say in Star Wars, Luke Skywalker trust the force. That's from Joseph Campbell and mythology of allow the life force to flow through you. What I try to say now is, it's not about you; it just happens through you. I got up on the blocks, and I still can't remember the race. I don't remember it. I was going so fast. So like in these rates, I was swimming butterfly, and you time your turns so that you can hit it just right. And if you don't time it right, then you can almost come to a dead stop.

[00:54:36] Seth Pepper
And I was going so fast that I was missing every single turn. And there is three turns out of this four lengths, so you can imagine that that's going to slow things down a lot. Because I flipped this switch, and all of a sudden I was in this race car that had been racing at the highest level, and now I have a turbo. I didn't even know there was a turbo. I destroyed the field and I missed the American record by two inches, missing all those walls. And I don't remember any of it. That to me was the transcendence that was created this curiosity, and you could if faith isn't your thing, then you can go over to maybe the more scientific side. That's the subconscious mind that supercomputer in your muscle memory, just riding your bike, just driving your car, you just let the car drive itself right.

[00:55:34] Seth Pepper
Or you think about the team first versus yourself. So that's where I've really found this to be explosive in a great, great way is that you start to show this and share this, and then people have their own 'f it' moment. Then they want to know tools on how do you get closer to that so that it can happen more often? And for longer periods. And I think that all of us want to understand how as a human being can we function to the highest level more often and longer. How can we be our best self? And that's really the unlimited version of ourselves. So ultimately, I won the national championship. And this is straight out of like a movie because guess who's there? I couldn't have even planned it this way. Pablo Morales, this guy that I had on the wall.

[00:56:34] Seth Pepper
Programming my subconscious mind all the time, he handed me the national championship trophy. True story, full circle. There he is; I manifested that. But I am also going to share the flip of that, which is you can manifest stuff that you didn't even like. You got to be careful or specific because he came into my life one more time and he delivered me something else. He came out of retirement. I remember when on the pool deck someone gave me the headline that Paul would come out of retirement. I still remember that feeling in my gut, like oh no. So I go to the next Olympic trials and I have to race against my idol. There, he is in a swimsuit and I am going head to head with this guy, and he ended up beating me.

[00:57:33] Seth Pepper
And he took the spot on the Olympic team that I would have taken. That is the story that never heals. That's what feeds me. That's what this podcast is about. It's not just about winning; it's about extreme failure too. Because all of us, if you are one of the greats, you've had extreme failure on a regular basis. You actually welcome it. It's that relationship that you have to. Failure and pressure. And kind of like the tools that we put in place so that you can be at your best. And I think that's the exciting part about all of this to explore it, on a very real level. It's funny to be now described in any sort of context of 'why'.

[00:58:32] Seth Pepper
It's kind of like it would be metaphoric. You see it all the time in books, whether it might be the Bible or it could be children's books. Where do you want to hide something? The most powerful thing in the world, put it inside, put it right in front of your face. So that's what you know if there is a wisdom to it, it's just, I am going to stay here, right here, because I know how simple it is. And I am going to bring people into your environment that are going to create more evidence that 'hey, is it really that simple?' Because you are around someone or you are someone and they're going to say, 'Yeah, it is really that simple. It really is that simple.' But you got to stick with the simple because the mind is going to try and jump ahead. The mind is going to try and find something that's flashy.

[00:59:28] Seth Pepper
Create this necessity of new newness, and so that's I like to just say, power hides in the obvious. That's the perfect place to put it. It's just so obvious. So I'll tell people straight up: I am not going to teach you anything new. I am not here to teach you anything new. You already know this stuff. I am just bringing it to the top, and we're going to keep it at the top. And we're going to have accountability check in on: 'Is this simple? Did you do this simple?' 'Did you do this simple?' 'Did you do this simple?' And that's the power. It's not about making this into some sort of new catchphrase. It's not into some sophisticated sort of scientific discovery or new tech.

[01:00:27] Seth Pepper
Those might support this a bit here and there, but it really is going to be you. You already know what works. You just have to choose where you want to go and stick with what works to get there. And if you can take off any sort of limitation, imagine what you can do. I have all kinds of crazy stories that I can share. The part along the way was that my brother, who's two years younger than me, he started even later than I did. I started when I was fourteen; he started when I was seventeen. He started for different reasons because he just saw how many friends I had. So he started following me to the pool and then he's going to take an interest in what I am doing. And so, I was like trying to help him on the mental side of things. And he was my first person.

[01:01:25] Seth Pepper
He's in Oregon and I am in Arizona. He integrates school, and I used to send home scripts for visualization. And I'd say, "I want because you are going to trust your voice, so I want you to be recording this and listening to this." What are your goals? Let's talk about the subconscious mind stuff like that, like the mechanical part of the mind. Put all those things a lot of the stuff that I do now. Of course now, evolved into a lot more as well. He went to the university and he too became a national champion. We are the first brothers in the history of swimming to win the same national championship. We also did it on the world stage where we both won world championship medals, the first brothers to ever do it. We started super late. We are completely opposite personalities doing it for different reasons.

[01:02:23] Seth Pepper
Yet we arrived at the same level of greatness. An aside from my brother is his goal. He didn't really want to be a great athlete because, ironic like he just wanted to beat his brother, was what my coach Rick had figured out. So when he was behind the start, Rick just said to him, "Hey, your brother did this. You know you can too." That's all my brother needed to hear. So it was sibling rivalry, maybe, but his goal really was to have his own show on the Discovery Channel. And so I was like, "Well, the power of the mind's got to work, not just in sports, it could work in entertainment." And so what we did is we went and I taught myself. We were self-learners; like everything is just self-taught. So I taught myself how to use a video camera, how to do some editing all from scratch.

[01:03:21] Seth Pepper
Taught myself how to make the graphics for the Discovery Channel, and we just built it. We shot it, we built it, we put it out in the world. We did it. That's the effort switch: just go do it. Break all the rules. Don't wait for castings, don't wait for producers, just go do it. Put it out there. It is a true story. Three years later, Discovery Channel producer came to us, and my brother got his own show on the Discovery Channel. It wasn't Nat Geo. It wasn't the History Channel. It was exactly what he wanted. It works. The stuff works. And I have story after story that we're going to share along the way of people winning Emmys, people having the number one Netflix movie in their journey story. And we're going to hear obviously about all the high level profile people winning sports awards as well.

[01:04:18] Seth Pepper
And just get into this stuff and kind of geek out. I think it'll be an inclusive kind of geek out where you'll be able to relate because it's really super simple. As we wrap up today's episode, I want to remind you of this: your potential is not something that you discover once. It's something that you choose every single day. It's built in the quiet moments, in the discipline to show up when no one is watching, in the courage to grow and stay comfortable. Everything you need to rise to the next level is already inside you. Your job is to commit to it, to train it, to protect it. If today's conversation added value to your life, be sure to subscribe, leave a comment, and share this episode with someone who's ready to elevate. And remember, greatness isn't accidental; it's intentional. This is Seth Pepper and this is Unlimit Your Potential. Keep growing, keep leading.

[01:05:17] Seth Pepper
Keep it coming. I'll see you next time.
`;
